<a href="https://colab.research.google.com/github/cpython-projects/python_da_17_03_26/blob/main/lesson_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Регулярні вирази** — це формальна мова для опису шаблонів у тексті.

Використовуються для:

* **пошуку**
* **витягання**
* **заміни**
* **валідації** фрагментів тексту.

**Приклади аналітичних завдань:**

* Перевірити, що значення — email
* Витягти домен з email
* Очистити номер телефону від зайвих символів
* Знайти лише ті рядки, де згадується подія
* Витягти дату з рядка

## БАЗОВІ ЕЛЕМЕНТИ РЕГУЛЯРНИХ ВИРАЗІВ

Регулярні вирази складаються з:

* **Символів-класів** (що шукати)
* **Квантифікаторів** (скільки разів)
* **Позиційних символів** (де саме)
* **Групування та логіки** (або, множини, групи)
* **Екранізації спецсимволів**

### I. Символи-класи (що шукати)

| Вираз | Назва     | Значення                         | Приклад                 |
| ----- | --------- | -------------------------------- | ----------------------- |
| `\d`  | digit     | цифра (0–9)                      | `\d+` — одна або більше |
| `\D`  | not digit | все, крім цифр                   | `\D+` — лише текст      |
| `\w`  | word      | літера, цифра або `_`            | `\w+` — слово           |
| `\W`  | not word  | все, крім `\w`                   | `\W+` — пробіли, знаки  |
| `\s`  | space     | пробіл, табуляція, перенос рядка | `\s+` — роздільники     |
| `\S`  | not space | не пробіл                        | `\S+` — щільний текст   |

📌 **Зауваження:**

* `\w` не включає кирилицю. Для українського тексту краще використовувати: `[а-яА-ЯёЁa-zA-Z0-9_]`.

### II. Позиційні символи (де шукати)

| Символ | Значення      | Приклад                          |
| ------ | ------------- | -------------------------------- |
| `^`    | початок рядка | `^ID` — починається з "ID"       |
| `$`    | кінець рядка  | `.com$` — закінчується на ".com" |
| `\b`   | межа слова    | `\bcat\b` — лише слово "cat"     |
| `\B`   | не межа слова | `\Bcat\B` — всередині слова      |

### III. Квантифікатори (скільки разів зустрічається)

| Вираз   | Значення             | Приклад                            |
| ------- | -------------------- | ---------------------------------- |
| `*`     | 0 або більше разів   | `\d*` — 0 і більше цифр            |
| `+`     | 1 або більше разів   | `\d+` — мінімум 1 цифра            |
| `?`     | 0 або 1 раз          | `s?` — літера s необов’язкова      |
| `{n}`   | рівно n разів        | `\d{4}` — 4 цифри (наприклад, рік) |
| `{n,}`  | від n разів і більше | `\d{2,}` — від двох цифр           |
| `{n,m}` | від n до m разів     | `\d{2,4}` — 2–4 цифри              |

### IV. Групування, альтернатива та множини

**1. Дужки `()` — групування**

Використовуються для створення **груп**, зручно з `str.extract()`:

* `(\d{4})-(\d{2})-(\d{2})` — витягає дату (рік, місяць, день)
* В pandas створюються окремі стовпці по групах

**2. Альтернатива `|` — або**

* `cat|dog|bird` — одне з слів
* `(http|https)://` — будь-який протокол

**3. Квадратні дужки `[]` — множини символів**

| Вираз    | Значення                    | Приклад             |
| -------- | --------------------------- | ------------------- |
| `[abc]`  | один із символів a, b або c | `[aeiou]` — голосні |
| `[a-z]`  | діапазон                    | `[0-9]` — цифри     |
| `[^a-z]` | все, крім вказаних          | `[^0-9]` — не цифри |

### V. Екранізація спецсимволів (Escape)

Регулярні вирази використовують **спецсимволи**, які потрібно екранувати `\`, якщо хочеш шукати їх буквально:

| Символ                      | Призначення       |
| --------------------------- | ----------------- |
| `\.`                        | крапка            |
| `\*`                        | зірочка           |
| `\\`                        | зворотний слеш    |
| `\+`, `\?`, `\(`, `\)` тощо | також екрануються |

**Приклад:**
`r"\.\w+"` — шукає крапку та слово після неї, наприклад: `.txt`, `.csv`.

## Приклади

### 1. **Символьні класи (попередньо визначені шаблони)**

| Регулярка | Що означає                | Приклад рядка                  | Знайде                                                                                                                                     |
| --------- | ------------------------- | ------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------ |
| `\d`      | Цифра (0–9)               | `'Вартість: 1200 грн'`         | `'1'`, `'2'`, `'0'`, `'0'`                                                                                                                 |
| `\D`      | Не цифра                  | `'Вартість: 1200 грн'`         | `'В'`, `'а'`, `'р'`, `'т'`, `'і'`, `'с'`, `'т'`, `'ь'`, `':'`, `' '`                                                                       |
| `\w`      | Літера/цифра/підкреслення | `'user_id_42'`                 | `'u'`, `'s'`, `'e'`, `'r'`, `'_'`, `'i'`, `'d'`, `'_'`, `'4'`, `'2'`                                                                       |
| `\W`      | Все, крім `\w`            | `'user#id!'`                   | `'#'`, `'!'`                                                                                                                               |
| `\s`      | Пробільний символ         | `'item1\titem2  item3\nitem4'` | `'\t'`, `' '`, `' '`, `'\n'`                                                                                                               |
| `\S`      | Не пробіл                 | `'item1\titem2  item3\nitem4'` | `'i'`, `'t'`, `'e'`, `'m'`, `'1'`, `'i'`, `'t'`, `'e'`, `'m'`, `'2'`, `'i'`, `'t'`, `'e'`, `'m'`, `'3'`, `'i'`, `'t'`, `'e'`, `'m'`, `'4'` |

---

### 2. **Явні символи**

| Регулярка | Що означає                  | Приклад             | Результат                  |
| --------- | --------------------------- | ------------------- | -------------------------- |
| `.`       | Будь-який символ, крім `\n` | `'a1#b'`            | `'a'`, `'1'`, `'#'`, `'b'` |
| `\.`      | Буквально крапка            | `'v1.2 file.txt'`   | `'.'`, `'.'`               |
| `\\`      | Буквально зворотний слеш    | `'C:\\Users\\Oleh'` | `'\\'`, `'\\'`             |

---

### 3. **Квантифікатори (повтори)**

| Регулярка | Опис             | Приклад    | Знайде                  |
| --------- | ---------------- | ---------- | ----------------------- |
| `a*`      | 0 або більше `a` | `'caaaat'` | `'aaaa'`                |
| `a+`      | 1 або більше `a` | `'caaaat'` | `'aaaa'`                |
| `a?`      | 0 або 1 `a`      | `'caaaat'` | `'a'` (перше входження) |
| `a{3}`    | Рівно 3 `a`      | `'aaaab'`  | `'aaa'`                 |
| `a{2,4}`  | Від 2 до 4 `a`   | `'aaaaaa'` | `'aaaa'`                |
| `a{2,}`   | 2 і більше `a`   | `'aaab'`   | `'aaa'`                 |

---

### 4. **Групи та діапазони**

| Регулярка  | Що означає                    | Приклад рядка | Результат                                |
| ---------- | ----------------------------- | ------------- | ---------------------------------------- |
| `[abc]`    | Один символ: a, b або c       | `'ball'`      | `'b'`, `'a'`                                    |
| `[^abc]`   | Все, крім a, b, c             | `'dog'`       | `'d'`, `'o'`, `'g'`                      |
| `[a-z]`    | Будь-яка мала латинська буква | `'data2025'`  | `'d'`, `'a'`, `'t'`, `'a'`               |
| `[0-9]`    | Цифри від 0 до 9              | `'v2025'`     | `'2'`, `'0'`, `'2'`, `'5'`               |
| `[A-Za-z]` | Будь-яка латинська буква      | `'UserID'`    | `'U'`, `'s'`, `'e'`, `'r'`, `'I'`, `'D'` |

---

### 5. **Групування та альтернативи**

| Регулярка | Що означає     | Приклад                    | Результат            |                            |                  |
| --------- | -------------- | -------------------------- | -------------------- | -------------------------- | ---------------- |
| `(abc)`   | Група символів | `'abcabc'`                 | `'abc'`, `'abc'`     |                            |                  |
| \`(cat    | dog            | bird)\`                    | Альтернатива         | `'I have a dog and a cat'` | `'dog'`, `'cat'` |
| \`(http   | https)://\`    | Альтернатива для протоколу | `'https://site.com'` | `'https://'`               |                  |

---

### 6. **Якорі (межі)**

| Регулярка | Що означає    | Приклад            | Результат |
| --------- | ------------- | ------------------ | --------- |
| `^abc`    | Початок рядка | `'abcdef'`         | `'abc'`   |
| `abc$`    | Кінець рядка  | `'zzzabc'`         | `'abc'`   |
| `\bcat\b` | Слово цілком  | `'a cat in a hat'` | `'cat'`   |

---

# Приклади

## 1. **Очистка телефонних номерів**

У датасеті є "сирі" номери:

```python
import pandas as pd

df = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "phone": ["+380 67 123-45-67", "0671234567", "38067123-45-67", "(067) 123 45 67"]
})
```

**Задача:** привести телефони до єдиного формату `+380XXXXXXXXX`.

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "phone": ["+380 67 123-45-67", "0671234567", "38067123-45-67", "(067) 123 45 67"]
})

In [ ]:
df

   customer_id              phone
0            1  +380 67 123-45-67
1            2         0671234567
2            3     38067123-45-67
3            4    (067) 123 45 67

In [ ]:
df['phone'] = df.phone.str.replace(r'\D', '', regex=True)
df

   customer_id         phone
0            1  380671234567
1            2    0671234567
2            3  380671234567
3            4    0671234567

In [ ]:
df['phone'] = df.phone.apply(lambda item: '+380' + item[-9:])
df

   customer_id          phone
0            1  +380671234567
1            2  +380671234567
2            3  +380671234567
3            4  +380671234567

### 2. **Виділення домену з email**

```python
df = pd.DataFrame({
    "email": ["user1@gmail.com", "manager@company.org", "test123@yahoo.com"]
})
```

**Задача:** отримати тільки домени (`gmail.com`, `company.org`...).

In [ ]:
df = pd.DataFrame({
    "email": ["user1@gmail.com", "manager@company.org", "test123@yahoo.com", "test56789@gmail"]
})
df

                 email
0      user1@gmail.com
1  manager@company.org
2    test123@yahoo.com
3      test56789@gmail

In [ ]:
df['email_domains'] = df.email.apply(lambda item: item.split('@')[1])
df

                 email email_domains
0      user1@gmail.com     gmail.com
1  manager@company.org   company.org
2    test123@yahoo.com     yahoo.com
3      test56789@gmail         gmail

In [ ]:
df['email_domains'] = df.email.str.extract(r'@(.+)$')
df['email_users'] = df.email.str.extract(r'^(.+)@')
df

                 email email_domains email_users
0      user1@gmail.com     gmail.com       user1
1  manager@company.org   company.org     manager
2    test123@yahoo.com     yahoo.com     test123
3      test56789@gmail         gmail   test56789

## 3. **Фільтрація рядків по шаблону**

Є список замовлень із кодами товарів:

```python
df = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "product_code": ["AB-12345", "CD-54321", "AB-67890", "XY-00000"]
})
```

**Задача:** знайти всі товари, що починаються на `AB-`.

In [ ]:
df = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105],
    "product_code": ["AB-12345", "CD-54321", "AB-67890", "XY-00000", "XB-12345"]
})
df

   order_id product_code
0       101     AB-12345
1       102     CD-54321
2       103     AB-67890
3       104     XY-00000
4       105     XB-12345

In [ ]:
df[df.product_code.str.startswith('AB-')]

   order_id product_code
0       101     AB-12345
2       103     AB-67890

In [ ]:
df[df.product_code.str.contains(r'^AB-')]

   order_id product_code
0       101     AB-12345
2       103     AB-67890

## 4. **Парсинг тексту на кілька колонок**

У колонці `address` зберігається рядок:

```
"Kyiv, Khreshchatyk 12, 01001"
```

```python
df = pd.DataFrame({
    "address": [
        "Kyiv, Khreshchatyk 12, 01001",
        "Lviv, Svobody Ave 25, 79000"
    ]
})
```

**Задача:** розбити на `city`, `street`, `postal_code`.

In [ ]:
df = pd.DataFrame({
    "address": [
        "Kyiv, Khreshchatyk 12, 01001",
        "Lviv, Svobody Ave 25, 79000"
    ]
})
df

                        address
0  Kyiv, Khreshchatyk 12, 01001
1   Lviv, Svobody Ave 25, 79000

In [ ]:
df[['city', 'street', 'post_index']] = df.address.str.extract(r'^([^,]+),\s*([^,]+),\s*(\d+)$')
df

                        address  city           street post_index
0  Kyiv, Khreshchatyk 12, 01001  Kyiv  Khreshchatyk 12      01001
1   Lviv, Svobody Ave 25, 79000  Lviv   Svobody Ave 25      79000

## 5. **Видалення HTML-тегів із тексту**

```python
df = pd.DataFrame({
    "review": [
        "<p>Good product!</p>",
        "<div>Average <b>quality</b></div>"
    ]
})
```

**Задача:** очистити текст від тегів.

In [ ]:
df = pd.DataFrame({
    "review": [
        "<p>Good product!</p>",
        "<div>Average <b>quality</b></div>"
    ]
})

df

                              review
0               <p>Good product!</p>
1  <div>Average <b>quality</b></div>

In [ ]:
df['clean_review'] = df.review.str.replace(r'<.+?>', '', regex=True)
df

                              review     clean_review
0               <p>Good product!</p>    Good product!
1  <div>Average <b>quality</b></div>  Average quality

## 6. **Виділення валюти та суми**

```python
df = pd.DataFrame({
    "price": ["USD 1200", "EUR 900", "UAH 45000"]
})
```

**Задача:** розбити на `currency` і `amount`.

In [ ]:
df = pd.DataFrame({
    "price": ["USD 1200", "EUR 900", "UAH       45 000"]
})

In [ ]:
df

              price
0          USD 1200
1           EUR 900
2  UAH       45 000

In [ ]:
df[['currency', 'value']] = df.price.str.extract(r'^(\w+)\s*([\d ]+)$')
df

              price currency   value
0          USD 1200      USD    1200
1           EUR 900      EUR     900
2  UAH       45 000      UAH  45 000

# Задачі

## 1. **Нормалізація номерів банківських карток**

У даних номери карток записані у різному вигляді.  
**Задача:** привести їх до єдиного формату `1234 5678 9012 3456`.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "card_number": [
        "1234-5678-9012-3456",
        "1234 5678 9012 3456",
        "1234567890123456"
    ]
})

In [ ]:
df

           card_number
0  1234-5678-9012-3456
1  1234 5678 9012 3456
2     1234567890123456

In [ ]:
df['clean_card_number'] = df.card_number.str.replace(r'\D', '', regex=True)
df

           card_number clean_card_number
0  1234-5678-9012-3456  1234567890123456
1  1234 5678 9012 3456  1234567890123456
2     1234567890123456  1234567890123456

In [ ]:
df['clean_card_number'] = df.clean_card_number.str.replace(r'([0-9]{4})(\d{4})(\d{4})(\d{4})', r'\1 \2 \3 \4', regex=True)
df

           card_number    clean_card_number
0  1234-5678-9012-3456  1234 5678 9012 3456
1  1234 5678 9012 3456  1234 5678 9012 3456
2     1234567890123456  1234 5678 9012 3456

## 2. **Виділення імені користувача з email**
**Задача:** отримати тільки ім’я користувача (до символа `@`).

In [1]:
import pandas as pd
df = pd.DataFrame({
    "email": ["anna.petrenko@company.com", "ivan1990@gmail.com", "data_analyst@org.ua"]
})

In [2]:
df

                       email
0  anna.petrenko@company.com
1         ivan1990@gmail.com
2        data_analyst@org.ua

In [4]:
df['username'] = df.email.str.extract(r'^(.+)@')
df

                       email       username
0  anna.petrenko@company.com  anna.petrenko
1         ivan1990@gmail.com       ivan1990
2        data_analyst@org.ua   data_analyst

## 3. **Фільтрація за артикулом товару**
**Задача:** вибрати тільки ті товари, що мають код починається на `SKU-`.

In [5]:
df = pd.DataFrame({
    "product_code": ["SKU-001-A", "SKU-002-B", "PRD-999-X", "SKU-003-C"]
})

In [6]:
df[df.product_code.str.startswith('SKU-')]

  product_code
0    SKU-001-A
1    SKU-002-B
3    SKU-003-C

## 4. **Аналіз одиниць виміру (вага)**

У даних вага вказана разом із одиницями виміру:  
**Задача 1:** дізнатися, які саме одиниці виміру зустрічаються (і скільки разів кожна).  
**Задача 2:** отримати числове значення окремо від одиниці.

In [7]:
df = pd.DataFrame({
    "weight": ["12 kg", "800 g", "1.5 kg", "300 g", "2 t", "750 g", "0.5 kg"]
})

In [11]:
df[['wieght_new', 'unit']] = df.weight.str.extract(r'([\d\.]+) (\D+)')
df

   weight wieght_new unit
0   12 kg         12   kg
1   800 g        800    g
2  1.5 kg        1.5   kg
3   300 g        300    g
4     2 t          2    t
5   750 g        750    g
6  0.5 kg        0.5   kg

In [13]:
df['wieght_new'] = df.wieght_new.astype('float')
df['unit'] = df.unit.astype('category')
df

   weight  wieght_new unit
0   12 kg        12.0   kg
1   800 g       800.0    g
2  1.5 kg         1.5   kg
3   300 g       300.0    g
4     2 t         2.0    t
5   750 g       750.0    g
6  0.5 kg         0.5   kg

In [14]:
df.unit.value_counts()

unit
g     3
kg    3
t     1
Name: count, dtype: int64