<a href="https://colab.research.google.com/github/cpython-projects/python_da_17_03_26/blob/main/lesson_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/cpython-projects/python_da_17_03_26/refs/heads/main/lesson_12_data.csv')
df

,Unnamed: 0,ID,Name,gender,Age,Salary ($),Hire Date,Country,Weight
0,0,1,Alice,F,25,50000.0,2023-01-10,USA,70kg
1,1,2,Bob,M,Thirty,60000.0,2022-12-05,U.S.A.,154lbs
2,2,3,CHARLIE,M,40,NaN,01/15/2021,UK,65kg
3,3,4,Dave,M,22,70000.0,"March 1, 2020",United Kingdom,140lbs
4,4,5,Eve,F,NaN,80000.0,2021-07-20,canada,75kg
5,5,6,Frank,M,35,120000.0,08/10/2019,Canada,165lbs
6,6,7,George,M,29,NaN,2020-05-30,Germany,80kg
7,7,8,Hannah,F,33,150000.0,"July 4, 2018",France,180lbs
8,8,9,Isaac,M,45,200000.0,06-01-2017,France,90kg
9,9,10,Jack,M,Twenty,250000.0,2016-09-15,Brazil,200lbs
10,10,5,Eve,F,NaN,80000.0,2021-07-20,canada,75kg
11,11,6,Frank,M,35,120000.0,08/10/2019,Canada,165lbs

# STEP 1

In [ ]:
df.columns.to_list()

['Unnamed: 0',
 'ID',
 'Name',
 'gender',
 'Age',
 'Salary ($)',
 'Hire Date',
 'Country',
 'Weight']

In [ ]:
df.drop(columns=['Unnamed: 0'], inplace=True)
df

,ID,Name,gender,Age,Salary ($),Hire Date,Country,Weight
0,1,Alice,F,25,50000.0,2023-01-10,USA,70kg
1,2,Bob,M,Thirty,60000.0,2022-12-05,U.S.A.,154lbs
2,3,CHARLIE,M,40,NaN,01/15/2021,UK,65kg
3,4,Dave,M,22,70000.0,"March 1, 2020",United Kingdom,140lbs
4,5,Eve,F,NaN,80000.0,2021-07-20,canada,75kg
5,6,Frank,M,35,120000.0,08/10/2019,Canada,165lbs
6,7,George,M,29,NaN,2020-05-30,Germany,80kg
7,8,Hannah,F,33,150000.0,"July 4, 2018",France,180lbs
8,9,Isaac,M,45,200000.0,06-01-2017,France,90kg
9,10,Jack,M,Twenty,250000.0,2016-09-15,Brazil,200lbs
10,5,Eve,F,NaN,80000.0,2021-07-20,canada,75kg
11,6,Frank,M,35,120000.0,08/10/2019,Canada,165lbs

In [ ]:
df.rename(columns={
    'ID': 'id',
    'Name': 'employee',
    'Age': 'age',
    'Salary ($)': 'employee_salary',
    'Hire Date': 'hire_date',
    'Country': 'country',
    'Weight': 'employee_weight'
}, inplace=True)
df

,id,employee,gender,age,employee_salary,hire_date,country,employee_weight
0,1,Alice,F,25,50000.0,2023-01-10,USA,70kg
1,2,Bob,M,Thirty,60000.0,2022-12-05,U.S.A.,154lbs
2,3,CHARLIE,M,40,NaN,01/15/2021,UK,65kg
3,4,Dave,M,22,70000.0,"March 1, 2020",United Kingdom,140lbs
4,5,Eve,F,NaN,80000.0,2021-07-20,canada,75kg
5,6,Frank,M,35,120000.0,08/10/2019,Canada,165lbs
6,7,George,M,29,NaN,2020-05-30,Germany,80kg
7,8,Hannah,F,33,150000.0,"July 4, 2018",France,180lbs
8,9,Isaac,M,45,200000.0,06-01-2017,France,90kg
9,10,Jack,M,Twenty,250000.0,2016-09-15,Brazil,200lbs
10,5,Eve,F,NaN,80000.0,2021-07-20,canada,75kg
11,6,Frank,M,35,120000.0,08/10/2019,Canada,165lbs

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               12 non-null     int64
 1   employee         12 non-null     object
 2   gender           12 non-null     object
 3   age              10 non-null     object
 4   employee_salary  10 non-null     float64
 5   hire_date        12 non-null     object
 6   country          12 non-null     object
 7   employee_weight  12 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 900.0+ bytes

# STEP 2

In [ ]:
df.duplicated().sum()

np.int64(2)

In [ ]:
df.drop_duplicates(inplace=True)
df

,id,employee,gender,age,employee_salary,hire_date,country,employee_weight
0,1,Alice,F,25,50000.0,2023-01-10,USA,70kg
1,2,Bob,M,Thirty,60000.0,2022-12-05,U.S.A.,154lbs
2,3,CHARLIE,M,40,NaN,01/15/2021,UK,65kg
3,4,Dave,M,22,70000.0,"March 1, 2020",United Kingdom,140lbs
4,5,Eve,F,NaN,80000.0,2021-07-20,canada,75kg
5,6,Frank,M,35,120000.0,08/10/2019,Canada,165lbs
6,7,George,M,29,NaN,2020-05-30,Germany,80kg
7,8,Hannah,F,33,150000.0,"July 4, 2018",France,180lbs
8,9,Isaac,M,45,200000.0,06-01-2017,France,90kg
9,10,Jack,M,Twenty,250000.0,2016-09-15,Brazil,200lbs

# STEP 3

In [ ]:
df['employee'] = df.employee.str.title()
df

,id,employee,gender,age,employee_salary,hire_date,country,employee_weight
0,1,Alice,F,25,50000.0,2023-01-10,USA,70kg
1,2,Bob,M,Thirty,60000.0,2022-12-05,U.S.A.,154lbs
2,3,Charlie,M,40,NaN,01/15/2021,UK,65kg
3,4,Dave,M,22,70000.0,"March 1, 2020",United Kingdom,140lbs
4,5,Eve,F,NaN,80000.0,2021-07-20,canada,75kg
5,6,Frank,M,35,120000.0,08/10/2019,Canada,165lbs
6,7,George,M,29,NaN,2020-05-30,Germany,80kg
7,8,Hannah,F,33,150000.0,"July 4, 2018",France,180lbs
8,9,Isaac,M,45,200000.0,06-01-2017,France,90kg
9,10,Jack,M,Twenty,250000.0,2016-09-15,Brazil,200lbs

In [ ]:
df.gender.unique()

array(['F', 'M'], dtype=object)

In [ ]:
df['gender'] = df.gender.astype('category')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               10 non-null     int64
 1   employee         10 non-null     object
 2   gender           10 non-null     category
 3   age              9 non-null      object
 4   employee_salary  8 non-null      float64
 5   hire_date        10 non-null     object
 6   country          10 non-null     object
 7   employee_weight  10 non-null     object
dtypes: category(1), float64(1), int64(1), object(5)
memory usage: 774.0+ bytes

In [ ]:
df.country.unique()

array(['Usa', 'U.S.A.', 'Uk', 'United Kingdom', 'Canada', 'Germany',
       'France', 'Brazil'], dtype=object)

In [ ]:
df['country'] = df.country.str.title()

In [ ]:
df['country'] = df.country.replace({
    'Usa': 'U.S.A.',
    'Uk': 'United Kingdom',
})

In [ ]:
df

,id,employee,gender,age,employee_salary,hire_date,country,employee_weight
0,1,Alice,F,25,50000.0,2023-01-10,U.S.A.,70kg
1,2,Bob,M,Thirty,60000.0,2022-12-05,U.S.A.,154lbs
2,3,Charlie,M,40,NaN,01/15/2021,United Kingdom,65kg
3,4,Dave,M,22,70000.0,"March 1, 2020",United Kingdom,140lbs
4,5,Eve,F,NaN,80000.0,2021-07-20,Canada,75kg
5,6,Frank,M,35,120000.0,08/10/2019,Canada,165lbs
6,7,George,M,29,NaN,2020-05-30,Germany,80kg
7,8,Hannah,F,33,150000.0,"July 4, 2018",France,180lbs
8,9,Isaac,M,45,200000.0,06-01-2017,France,90kg
9,10,Jack,M,Twenty,250000.0,2016-09-15,Brazil,200lbs

In [ ]:
df.age.unique()

array(['25', '30', '40', '22', nan, '35', '29', '33', '45', '20'],
      dtype=object)

In [ ]:
df['age'] = df.age.replace({
    'Thirty': '30',
    'Twenty': '20'
})

In [ ]:
df['age'] = df.age.astype('int')

ValueError: cannot convert float NaN to integer

In [ ]:
df['age'] = pd.to_numeric(df.age, errors='coerce')
df

,id,employee,gender,age,employee_salary,hire_date,country,employee_weight
0,1,Alice,F,25.0,50000.0,2023-01-10,U.S.A.,70kg
1,2,Bob,M,30.0,60000.0,2022-12-05,U.S.A.,154lbs
2,3,Charlie,M,40.0,NaN,01/15/2021,United Kingdom,65kg
3,4,Dave,M,22.0,70000.0,"March 1, 2020",United Kingdom,140lbs
4,5,Eve,F,NaN,80000.0,2021-07-20,Canada,75kg
5,6,Frank,M,35.0,120000.0,08/10/2019,Canada,165lbs
6,7,George,M,29.0,NaN,2020-05-30,Germany,80kg
7,8,Hannah,F,33.0,150000.0,"July 4, 2018",France,180lbs
8,9,Isaac,M,45.0,200000.0,06-01-2017,France,90kg
9,10,Jack,M,20.0,250000.0,2016-09-15,Brazil,200lbs

In [ ]:
df['age'] = df.age.fillna(df.age.mean())
df['age'] = df.age.astype('int')
df

,id,employee,gender,age,employee_salary,hire_date,country,employee_weight
0,1,Alice,F,25,50000.0,2023-01-10,U.S.A.,70kg
1,2,Bob,M,30,60000.0,2022-12-05,U.S.A.,154lbs
2,3,Charlie,M,40,NaN,01/15/2021,United Kingdom,65kg
3,4,Dave,M,22,70000.0,"March 1, 2020",United Kingdom,140lbs
4,5,Eve,F,31,80000.0,2021-07-20,Canada,75kg
5,6,Frank,M,35,120000.0,08/10/2019,Canada,165lbs
6,7,George,M,29,NaN,2020-05-30,Germany,80kg
7,8,Hannah,F,33,150000.0,"July 4, 2018",France,180lbs
8,9,Isaac,M,45,200000.0,06-01-2017,France,90kg
9,10,Jack,M,20,250000.0,2016-09-15,Brazil,200lbs

In [ ]:
df['new_date'] = pd.to_datetime(df.hire_date, errors='coerce')
df

,id,employee,gender,age,employee_salary,hire_date,country,employee_weight,new_date
0,1,Alice,F,25,50000.0,2023-01-10,U.S.A.,70kg,2023-01-10
1,2,Bob,M,30,60000.0,2022-12-05,U.S.A.,154lbs,2022-12-05
2,3,Charlie,M,40,NaN,01/15/2021,United Kingdom,65kg,NaT
3,4,Dave,M,22,70000.0,"March 1, 2020",United Kingdom,140lbs,NaT
4,5,Eve,F,31,80000.0,2021-07-20,Canada,75kg,2021-07-20
5,6,Frank,M,35,120000.0,08/10/2019,Canada,165lbs,NaT
6,7,George,M,29,NaN,2020-05-30,Germany,80kg,2020-05-30
7,8,Hannah,F,33,150000.0,"July 4, 2018",France,180lbs,NaT
8,9,Isaac,M,45,200000.0,06-01-2017,France,90kg,NaT
9,10,Jack,M,20,250000.0,2016-09-15,Brazil,200lbs,2016-09-15

In [ ]:
from dateutil import parser

In [ ]:
df['hire_date'] = df.hire_date.apply(parser.parse)
df

,id,employee,gender,age,employee_salary,hire_date,country,employee_weight,new_date
0,1,Alice,F,25,50000.0,2023-01-10,U.S.A.,70kg,2023-01-10
1,2,Bob,M,30,60000.0,2022-12-05,U.S.A.,154lbs,2022-12-05
2,3,Charlie,M,40,NaN,2021-01-15,United Kingdom,65kg,NaT
3,4,Dave,M,22,70000.0,2020-03-01,United Kingdom,140lbs,NaT
4,5,Eve,F,31,80000.0,2021-07-20,Canada,75kg,2021-07-20
5,6,Frank,M,35,120000.0,2019-08-10,Canada,165lbs,NaT
6,7,George,M,29,NaN,2020-05-30,Germany,80kg,2020-05-30
7,8,Hannah,F,33,150000.0,2018-07-04,France,180lbs,NaT
8,9,Isaac,M,45,200000.0,2017-06-01,France,90kg,NaT
9,10,Jack,M,20,250000.0,2016-09-15,Brazil,200lbs,2016-09-15

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               10 non-null     int64
 1   employee         10 non-null     object
 2   gender           10 non-null     category
 3   age              10 non-null     int64
 4   employee_salary  8 non-null      float64
 5   hire_date        10 non-null     datetime64[ns]
 6   country          10 non-null     object
 7   employee_weight  10 non-null     object
 8   new_date         5 non-null      datetime64[ns]
dtypes: category(1), datetime64[ns](2), float64(1), int64(2), object(3)
memory usage: 854.0+ bytes

In [ ]:
def convert_weight(item):
  item = item.lower().strip()
  if 'kg' in item:
    return float(item.replace('kg', ''))

  if 'lbs' in item:
    return float(item.replace('lbs', '')) * 0.45345678

  return float(item)

df['weight_kg'] = df.employee_weight.apply(convert_weight)
df

,id,employee,gender,age,employee_salary,hire_date,country,employee_weight,new_date,weight_kg
0,1,Alice,F,25,50000.0,2023-01-10,U.S.A.,70kg,2023-01-10,70.000000
1,2,Bob,M,30,60000.0,2022-12-05,U.S.A.,154lbs,2022-12-05,69.832344
2,3,Charlie,M,40,NaN,2021-01-15,United Kingdom,65kg,NaT,65.000000
3,4,Dave,M,22,70000.0,2020-03-01,United Kingdom,140lbs,NaT,63.483949
4,5,Eve,F,31,80000.0,2021-07-20,Canada,75kg,2021-07-20,75.000000
5,6,Frank,M,35,120000.0,2019-08-10,Canada,165lbs,NaT,74.820369
6,7,George,M,29,NaN,2020-05-30,Germany,80kg,2020-05-30,80.000000
7,8,Hannah,F,33,150000.0,2018-07-04,France,180lbs,NaT,81.622220
8,9,Isaac,M,45,200000.0,2017-06-01,France,90kg,NaT,90.000000
9,10,Jack,M,20,250000.0,2016-09-15,Brazil,200lbs,2016-09-15,90.691356

In [ ]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [ ]:
df

,id,employee,gender,age,employee_salary,hire_date,country,employee_weight,new_date,weight_kg
0,1,Alice,F,25,50000.00,2023-01-10,U.S.A.,70kg,2023-01-10,70.00
1,2,Bob,M,30,60000.00,2022-12-05,U.S.A.,154lbs,2022-12-05,69.83
2,3,Charlie,M,40,NaN,2021-01-15,United Kingdom,65kg,NaT,65.00
3,4,Dave,M,22,70000.00,2020-03-01,United Kingdom,140lbs,NaT,63.48
4,5,Eve,F,31,80000.00,2021-07-20,Canada,75kg,2021-07-20,75.00
5,6,Frank,M,35,120000.00,2019-08-10,Canada,165lbs,NaT,74.82
6,7,George,M,29,NaN,2020-05-30,Germany,80kg,2020-05-30,80.00
7,8,Hannah,F,33,150000.00,2018-07-04,France,180lbs,NaT,81.62
8,9,Isaac,M,45,200000.00,2017-06-01,France,90kg,NaT,90.00
9,10,Jack,M,20,250000.00,2016-09-15,Brazil,200lbs,2016-09-15,90.69

In [ ]:
import warnings

warnings.filterwarnings('ignore')