<a href="https://colab.research.google.com/github/cpython-projects/python_da_17_03_26/blob/main/lesson_29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Що таке API

## API (Application Programming Interface)

* Це «програма для спілкування з програмою».
* Через API можна отримувати дані від зовнішніх сервісів.
* Часто використовується формат **JSON**.

## Типи API

* **Публічні** (без авторизації): можна одразу робити запит.
* **З авторизацією**: потрібен ключ (`api_key` або `token`) — як пароль.

## Де шукати API

* На сайтах сервісів → розділ *Developers* або *API Docs*
* Приклади:

  * [CoinGecko API (без ключа)](https://www.coingecko.com/en/api/documentation)
  * [CoinMarketCap API (потрібен ключ)](https://coinmarketcap.com/api/)
  * [OpenWeatherMap](https://openweathermap.org/api)
  * [NASA API](https://api.nasa.gov/)

## JSON — формат обміну даними в API

**JSON (JavaScript Object Notation)** — це текстовий формат передачі даних, який найчастіше повертають API.

Типовий JSON виглядає так:

```json
{
  "user_id": 101,
  "name": "Anna",
  "city": "Batumi",
  "orders": [
    {
      "order_id": 5001,
      "amount": 120.5,
      "status": "completed"
    },
    {
      "order_id": 5002,
      "amount": 75.0,
      "status": "pending"
    }
  ],
  "is_active": true
}
```

### Основні типи даних у JSON:

* `string` → `"Batumi"`
* `number` → `120.5`
* `boolean` → `true / false`
* `array` → `[ {...}, {...} ]`
* `object` → `{ "key": value }`
* `null`

> **Важливо:** JSON — це **рядок тексту**, а не Python-обʼєкт.


## Серіалізація і десеріалізація (ключове поняття)

### Серіалізація

**Серіалізація** — це процес **перетворення Python-обʼєкта у JSON-рядок**, щоб:

* передати його через API
* зберегти у файл
* відправити по мережі

In [ ]:
data = {
    "user_id": 101,
    "name": "Anna",
    "city": "Batumi"
}

In [ ]:
data

{'user_id': 101, 'name': 'Anna', 'city': 'Batumi'}

In [ ]:
import json
json_string = json.dumps(data)
json_string

'{"user_id": 101, "name": "Anna", "city": "Batumi"}'

In [ ]:
type(json_string)

str


### Десеріалізація

**Десеріалізація** — це зворотній процес:
**JSON → Python-обʼєкт**

In [ ]:
json_string = '{"user_id": 101, "name": "Anna", "city": "Batumi"}'

python_data = json.loads(json_string)
python_data

{'user_id': 101, 'name': 'Anna', 'city': 'Batumi'}

## Як це виглядає при роботі з API

In [1]:
import requests

url = "https://jsonplaceholder.typicode.com/users/1"
response = requests.get(url)

In [2]:
response.text

'{\n  "id": 1,\n  "name": "Leanne Graham",\n  "username": "Bret",\n  "email": "Sincere@april.biz",\n  "address": {\n    "street": "Kulas Light",\n    "suite": "Apt. 556",\n    "city": "Gwenborough",\n    "zipcode": "92998-3874",\n    "geo": {\n      "lat": "-37.3159",\n      "lng": "81.1496"\n    }\n  },\n  "phone": "1-770-736-8031 x56442",\n  "website": "hildegard.org",\n  "company": {\n    "name": "Romaguera-Crona",\n    "catchPhrase": "Multi-layered client-server neural-net",\n    "bs": "harness real-time e-markets"\n  }\n}'

In [3]:
type(response.text)

str

In [4]:
data = response.json()
data

{'id': 1,
 'name': 'Leanne Graham',
 'username': 'Bret',
 'email': 'Sincere@april.biz',
 'address': {'street': 'Kulas Light',
  'suite': 'Apt. 556',
  'city': 'Gwenborough',
  'zipcode': '92998-3874',
  'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
 'phone': '1-770-736-8031 x56442',
 'website': 'hildegard.org',
 'company': {'name': 'Romaguera-Crona',
  'catchPhrase': 'Multi-layered client-server neural-net',
  'bs': 'harness real-time e-markets'}}

In [5]:
type(data)

dict

In [6]:
data['phone']

'1-770-736-8031 x56442'

In [7]:
for key, value in data.items():
  print(key, value)

id 1
name Leanne Graham
username Bret
email Sincere@april.biz
address {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}
phone 1-770-736-8031 x56442
website hildegard.org
company {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}

## Перетворення JSON → Pandas DataFrame

Приклад API, що повертає список обʼєктів:

In [8]:
data = [
  {"date": "2025-01-01", "revenue": 1200},
  {"date": "2025-01-02", "revenue": 1500},
  {"date": "2025-01-03", "revenue": 1100}
]

import pandas as pd

df = pd.DataFrame(data)
df

         date  revenue
0  2025-01-01     1200
1  2025-01-02     1500
2  2025-01-03     1100

In [9]:
import requests

url = "https://jsonplaceholder.typicode.com/users/"
response = requests.get(url)

In [10]:
data = response.json()

In [12]:
data

[{'id': 1,
  'name': 'Leanne Graham',
  'username': 'Bret',
  'email': 'Sincere@april.biz',
  'address': {'street': 'Kulas Light',
   'suite': 'Apt. 556',
   'city': 'Gwenborough',
   'zipcode': '92998-3874',
   'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
  'phone': '1-770-736-8031 x56442',
  'website': 'hildegard.org',
  'company': {'name': 'Romaguera-Crona',
   'catchPhrase': 'Multi-layered client-server neural-net',
   'bs': 'harness real-time e-markets'}},
 {'id': 2,
  'name': 'Ervin Howell',
  'username': 'Antonette',
  'email': 'Shanna@melissa.tv',
  'address': {'street': 'Victor Plains',
   'suite': 'Suite 879',
   'city': 'Wisokyburgh',
   'zipcode': '90566-7771',
   'geo': {'lat': '-43.9509', 'lng': '-34.4618'}},
  'phone': '010-692-6593 x09125',
  'website': 'anastasia.net',
  'company': {'name': 'Deckow-Crist',
   'catchPhrase': 'Proactive didactic contingency',
   'bs': 'synergize scalable supply-chains'}},
 {'id': 3,
  'name': 'Clementine Bauch',
  'username': 'Samantha',
  'email': 'Nathan@yesenia.net',
  'address': {'street': 'Douglas Extension',
   'suite': 'Suite 847',
   'city': 'McKenziehaven',
   'zipcode': '59590-4157',
   'geo': {'lat': '-68.6102', 'lng': '-47.0653'}},
  'phone': '1-463-123-4447',
  'website': 'ramiro.info',
  'company': {'name': 'Romaguera-Jacobson',
   'catchPhrase': 'Face to face bifurcated interface',
   'bs': 'e-enable strategic applications'}},
 {'id': 4,
  'name': 'Patricia Lebsack',
  'username': 'Karianne',
  'email': 'Julianne.OConner@kory.org',
  'address': {'street': 'Hoeger Mall',
   'suite': 'Apt. 692',
   'city': 'South Elvis',
   'zipcode': '53919-4257',
   'geo': {'lat': '29.4572', 'lng': '-164.2990'}},
  'phone': '493-170-9623 x156',
  'website': 'kale.biz',
  'company': {'name': 'Robel-Corkery',
   'catchPhrase': 'Multi-tiered zero tolerance productivity',
   'bs': 'transition cutting-edge web services'}},
 {'id': 5,
  'name': 'Chelsey Dietrich',
  'username': 'Kamren',
  'email': 'Lucio_Hettinger@annie.ca',
  'address': {'street': 'Skiles Walks',
   'suite': 'Suite 351',
   'city': 'Roscoeview',
   'zipcode': '33263',
   'geo': {'lat': '-31.8129', 'lng': '62.5342'}},
  'phone': '(254)954-1289',
  'website': 'demarco.info',
  'company': {'name': 'Keebler LLC',
   'catchPhrase': 'User-centric fault-tolerant solution',
   'bs': 'revolutionize end-to-end systems'}},
 {'id': 6,
  'name': 'Mrs. Dennis Schulist',
  'username': 'Leopoldo_Corkery',
  'email': 'Karley_Dach@jasper.info',
  'address': {'street': 'Norberto Crossing',
   'suite': 'Apt. 950',
   'city': 'South Christy',
   'zipcode': '23505-1337',
   'geo': {'lat': '-71.4197', 'lng': '71.7478'}},
  'phone': '1-477-935-8478 x6430',
  'website': 'ola.org',
  'company': {'name': 'Considine-Lockman',
   'catchPhrase': 'Synchronised bottom-line interface',
   'bs': 'e-enable innovative applications'}},
 {'id': 7,
  'name': 'Kurtis Weissnat',
  'username': 'Elwyn.Skiles',
  'email': 'Telly.Hoeger@billy.biz',
  'address': {'street': 'Rex Trail',
   'suite': 'Suite 280',
   'city': 'Howemouth',
   'zipcode': '58804-1099',
   'geo': {'lat': '24.8918', 'lng': '21.8984'}},
  'phone': '210.067.6132',
  'website': 'elvis.io',
  'company': {'name': 'Johns Group',
   'catchPhrase': 'Configurable multimedia task-force',
   'bs': 'generate enterprise e-tailers'}},
 {'id': 8,
  'name': 'Nicholas Runolfsdottir V',
  'username': 'Maxime_Nienow',
  'email': 'Sherwood@rosamond.me',
  'address': {'street': 'Ellsworth Summit',
   'suite': 'Suite 729',
   'city': 'Aliyaview',
   'zipcode': '45169',
   'geo': {'lat': '-14.3990', 'lng': '-120.7677'}},
  'phone': '586.493.6943 x140',
  'website': 'jacynthe.com',
  'company': {'name': 'Abernathy Group',
   'catchPhrase': 'Implemented secondary concept',
   'bs': 'e-enable extensible e-tailers'}},
 {'id': 9,
  'name': 'Glenna Reichert',
  'username': 'Delphine',
  'email': 'Chaim_McDermott@dana.io',
  'address': {'street': 'Dayna Park',
   'suite': 'Suite 449',
   'city': 'Bartholomebury',
   'zipcode': '76495-3109',
   'geo': {'lat': '24.6463', 'lng': '-168.8889'}},
  'phone': '(775)976-6794 x41206',
  'website': 'conrad.com',
  'company': {'name': 'Yost and Sons',
   'catchPhrase': 'Switchable contextually-based project',
   'bs': 'aggregate real-time technologies'}},
 {'id': 10,
  'name': 'Clementina DuBuque',
  'username': 'Moriah.Stanton',
  'email': 'Rey.Padberg@karina.biz',
  'address': {'street': 'Kattie Turnpike',
   'suite': 'Suite 198',
   'city': 'Lebsackbury',
   'zipcode': '31428-2261',
   'geo': {'lat': '-38.2386', 'lng': '57.2232'}},
  'phone': '024-648-3804',
  'website': 'ambrose.net',
  'company': {'name': 'Hoeger LLC',
   'catchPhrase': 'Centralized empowering task-force',
   'bs': 'target end-to-end models'}}]

In [11]:
df = pd.DataFrame(data)
df

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [13]:
url

'https://jsonplaceholder.typicode.com/users/'

In [14]:
df = pd.read_json(url)
df

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

## Вкладені JSON

In [15]:
data = {
  "user_id": 101,
  "orders": [
    {"order_id": 1, "amount": 120},
    {"order_id": 2, "amount": 75}
  ]
}

df = pd.json_normalize(data, record_path="orders")
df

   order_id  amount
0         1     120
1         2      75

# Робота з публічним API (CoinGecko)

**Знайдемо потрібний endpoint**

* Документація CoinGecko: [https://www.coingecko.com/en/api/documentation](https://www.coingecko.com/en/api/documentation)
* Обираємо: `/coins/markets`

```http
GET https://api.coingecko.com/api/v3/coins/markets
?vs_currency=usd&order=market_cap_desc&per_page=10&page=1
```

**Надішлемо запит через Python**

In [16]:
import requests

url = "https://api.coingecko.com/api/v3/coins/markets"
params = {
    "vs_currency": "usd",
    "order": "market_cap_desc",
    "per_page": 10,
    "page": 1
}

response = requests.get(url, params=params)
print(response.status_code)
data = response.json()

200

In [17]:
data

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 66536,
  'market_cap': 1334659979789,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 1334660778212,
  'total_volume': 27560578385,
  'high_24h': 66840,
  'low_24h': 65027,
  'price_change_24h': 1142.63,
  'price_change_percentage_24h': 1.74732,
  'market_cap_change_24h': 22903816608,
  'market_cap_change_percentage_24h': 1.74604,
  'circulating_supply': 20059428.0,
  'total_supply': 20059440.0,
  'max_supply': 21000000.0,
  'ath': 126080,
  'ath_change_percentage': -47.22721,
  'ath_date': '2025-10-06T18:57:42.558Z',
  'atl': 67.81,
  'atl_change_percentage': 98022.4784,
  'atl_date': '2013-07-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-07-21T16:36:26.499Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 1924.39,
  'market_cap': 232240678776,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 232240678776,
  'total_volume': 12100029155,
  'high_24h': 1946.42,
  'low_24h': 1892.04,
  'price_change_24h': 24.96,
  'price_change_percentage_24h': 1.31427,
  'market_cap_change_24h': 2979357285,
  'market_cap_change_percentage_24h': 1.29955,
  'circulating_supply': 120682803.0755918,
  'total_supply': 120682803.0755918,
  'max_supply': None,
  'ath': 4946.05,
  'ath_change_percentage': -61.09227,
  'ath_date': '2025-08-24T19:21:03.333Z',
  'atl': 0.432979,
  'atl_change_percentage': 444354.73794,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 37.66975174871353,
   'currency': 'btc',
   'percentage': 3766.9751748713534},
  'last_updated': '2026-07-21T16:36:26.464Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 0.999381,
  'market_cap': 184104706471,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 189568243299,
  'total_volume': 48009305508,
  'high_24h': 0.999442,
  'low_24h': 0.999039,
  'price_change_24h': 0.00030345,
  'price_change_percentage_24h': 0.03037,
  'market_cap_change_24h': 51698587,
  'market_cap_change_percentage_24h': 0.02809,
  'circulating_supply': 184219443473.5799,
  'total_supply': 189686385265.5962,
  'max_supply': None,
  'ath': 1.32,
  'ath_change_percentage': -24.46631,
  'ath_date': '2018-07-24T00:00:00.000Z',
  'atl': 0.572521,
  'atl_change_percentage': 74.55827,
  'atl_date': '2015-03-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-07-21T16:36:24.800Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 574.28,
  'market_cap': 76473728959,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 76473728218,
  'total_volume': 624489647,
  'high_24h': 578.99,
  'low_24h': 569.6,
  'price_change_24h': 1.28,
  'price_change_percentage_24h': 0.22409,
  'market_cap_change_24h': 166426341,
  'market_cap_change_percentage_24h': 0.2181,
  'circulating_supply': 133165883.47,
  'total_supply': 133165882.18,
  'max_supply': 200000000.0,
  'ath': 1369.99,
  'ath_change_percentage': -58.08159,
  'ath_date': '2025-10-13T08:41:24.131Z',
  'atl': 0.0398177,
  'atl_change_percentage': 1442170.10562,
  'atl_date': '2017-10-19T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-07-21T16:36:26.347Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 0.999868,
  'market_cap': 73236660731,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 73237654495,
  'total_volume': 11854136647,
  'high_24h': 0.999966,
  'low_24h': 0.999727,
  'price_change_24h': 9.564e-05,
  'price_change_percentage_24h': 0.00957,
  'market_cap_change_24h': 65165409,
  'market_cap_change_percentage_24h': 0.08906,
  'circulating_supply': 73246329146.93828,
  'total_supply': 73247323041.8707,
  'max_supply': None,
  'ath': 1.043,
  'ath_change_percentage': -4.17628,
  'ath_date': '2018-11-15T00:00:00.000Z',
  'atl': 0.877647,
  'atl_change_percentage': 13.92816,
  'atl_date': '2023-03-11T08:02:13.981Z',
  'roi': None,
  'last_updated': '2026-07-21T16:36:11.883Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 1.15,
  'market_cap': 71830507807,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 114973927577,
  'total_volume': 1363496827,
  'high_24h': 1.15,
  'low_24h': 1.11,
  'price_change_24h': 0.03872393,
  'price_change_percentage_24h': 3.48494,
  'market_cap_change_24h': 2420482957,
  'market_cap_change_percentage_24h': 3.48722,
  'circulating_supply': 62466503703.0,
  'total_supply': 99985639695.0,
  'max_supply': 100000000000.0,
  'ath': 3.65,
  'ath_change_percentage': -68.46448,
  'ath_date': '2025-07-18T03:40:53.808Z',
  'atl': 0.00268621,
  'atl_change_percentage': 42707.74156,
  'atl_date': '2014-05-22T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-07-21T16:36:08.333Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 78.02,
  'market_cap': 45454744209,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 49198090408,
  'total_volume': 1702246514,
  'high_24h': 78.64,
  'low_24h': 77.37,
  'price_change_24h': 0.442614,
  'price_change_percentage_24h': 0.57058,
  'market_cap_change_24h': 258528667,
  'market_cap_change_percentage_24h': 0.57201,
  'circulating_supply': 582749333.1790326,
  'total_supply': 630740638.3617487,
  'max_supply': None,
  'ath': 293.31,
  'ath_change_percentage': -73.40198,
  'ath_date': '2025-01-19T11:15:27.957Z',
  'atl': 0.500801,
  'atl_change_percentage': 15478.06974,
  'atl_date': '2020-05-11T19:35:23.449Z',
  'roi': None,
  'last_updated': '2026-07-21T16:36:27.072Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/photo_2026-04-13_09-59-16.png?1776048311',
  'current_price': 0.328654,
  'market_cap': 31181056758,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 31181056439,
  'total_volume': 332693093,
  'high_24h': 0.328705,
  'low_24h': 0.325638,
  'price_change_24h': 0.00267465,
  'price_change_percentage_24h': 0.8205,
  'market_cap_change_24h': 254289527,
  'market_cap_change_percentage_24h': 0.82223,
  'circulating_supply': 94875121559.562,
  'total_supply': 94875120589.455,
  'max_supply': None,
  'ath': 0.431288,
  'ath_change_percentage': -23.79723,
  'ath_date': '2024-12-04T00:10:40.323Z',
  'atl': 0.00180434,
  'atl_change_percentage': 18114.60317,
  'atl_date': '2017-11-12T00:00:00.000Z',
  'roi': {'times': 171.97561504374332,
   'currency': 'usd',
   'percentage': 17197.56150437433},
  'last_updated': '2026-07-21T16:36:18.821Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 1.001,
  'market_cap': 20220814989,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 20220814989,
  'total_volume': 28774758,
  'high_24h': 1.008,
  'low_24h': 1.0,
  'price_change_24h': -0.007275299999999874,
  'price_change_percentage_24h': -0.72173,
  'market_cap_change_24h': -50337525.3731308,
  'market_cap_change_percentage_24h': -0.24832,
  'circulating_supply': 20205351833.508,
  'total_supply': 20205351833.508,
  'max_supply': None,
  'ath': 1.049,
  'ath_change_percentage': -4.60895,
  'ath_date': '2026-03-09T17:00:25.937Z',
  'atl': 0.155357,
  'atl_change_percentage': 544.17302,
  'atl_date': '2025-10-31T14:27:24.456Z',
  'roi': None,
  'last_updated': '2026-07-21T16:36:13.087Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 61.54,
  'market_cap': 13689048838,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 58788479339,
  'total_volume': 330327665,
  'high_24h': 63.3,
  'low_24h': 61.53,
  'price_change_24h': -0.6026566838868774,
  'price_change_percentage_24h': -0.96974,
  'market_cap_change_24h': -134483501.18567657,
  'market_cap_change_percentage_24h': -0.97286,
  'circulating_supply': 222445714.0741414,
  'total_supply': 955307079.4341414,
  'max_supply': 1000000000.0,
  'ath': 76.7,
  'ath_change_percentage': -19.76417,
  'ath_date': '2026-06-16T13:02:04.375Z',
  'atl': 3.81,
  'atl_change_percentage': 1515.8451,
  'atl_date': '2024-11-29T09:30:30.871Z',
  'roi': None,
  'last_updated': '2026-07-21T16:36:08.800Z'}]

In [ ]:
print(*data, sep='\n')

{'id': 'bitcoin', 'symbol': 'btc', 'name': 'Bitcoin', 'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400', 'current_price': 67244, 'market_cap': 1344086585055, 'market_cap_rank': 1, 'fully_diluted_valuation': 1344092703480, 'total_volume': 37397635769, 'high_24h': 69088, 'low_24h': 66725, 'price_change_24h': -828.888136182577, 'price_change_percentage_24h': -1.21765, 'market_cap_change_24h': -16893524867.760254, 'market_cap_change_percentage_24h': -1.24128, 'circulating_supply': 19990746.0, 'total_supply': 19990837.0, 'max_supply': 21000000.0, 'ath': 126080, 'ath_change_percentage': -46.66546, 'ath_date': '2025-10-06T18:57:42.558Z', 'atl': 67.81, 'atl_change_percentage': 99066.97338, 'atl_date': '2013-07-06T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-17T18:14:13.021Z'}
{'id': 'ethereum', 'symbol': 'eth', 'name': 'Ethereum', 'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628', 'current_price': 1964.58, 'market_cap': 237101071664, 'market_cap_rank': 2, 'fully_diluted_valuation': 237101071664, 'total_volume': 18686947147, 'high_24h': 2005.26, 'low_24h': 1946.07, 'price_change_24h': -17.097901083932356, 'price_change_percentage_24h': -0.8628, 'market_cap_change_24h': -2049093732.270996, 'market_cap_change_percentage_24h': -0.85682, 'circulating_supply': 120692440.4714584, 'total_supply': 120692440.4714584, 'max_supply': None, 'ath': 4946.05, 'ath_change_percentage': -60.27977, 'ath_date': '2025-08-24T19:21:03.333Z', 'atl': 0.432979, 'atl_change_percentage': 453636.22743, 'atl_date': '2015-10-20T00:00:00.000Z', 'roi': {'times': 38.06501391002879, 'currency': 'btc', 'percentage': 3806.501391002879}, 'last_updated': '2026-02-17T18:14:13.138Z'}
{'id': 'tether', 'symbol': 'usdt', 'name': 'Tether', 'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661', 'current_price': 0.999627, 'market_cap': 183683171397, 'market_cap_rank': 3, 'fully_diluted_valuation': 189148064233, 'total_volume': 63181495647, 'high_24h': 0.999822, 'low_24h': 0.999483, 'price_change_24h': 9.22e-06, 'price_change_percentage_24h': 0.00092, 'market_cap_change_24h': -19865504.12991333, 'market_cap_change_percentage_24h': -0.01081, 'circulating_supply': 183751887997.0696, 'total_supply': 189218825270.9362, 'max_supply': None, 'ath': 1.32, 'ath_change_percentage': -24.4488, 'ath_date': '2018-07-24T00:00:00.000Z', 'atl': 0.572521, 'atl_change_percentage': 74.59872, 'atl_date': '2015-03-02T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-17T18:14:18.777Z'}
{'id': 'ripple', 'symbol': 'xrp', 'name': 'XRP', 'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442', 'current_price': 1.47, 'market_cap': 89407322270, 'market_cap_rank': 4, 'fully_diluted_valuation': 146747366206, 'total_volume': 2298299303, 'high_24h': 1.49, 'low_24h': 1.43, 'price_change_24h': -0.01590422443956041, 'price_change_percentage_24h': -1.07199, 'market_cap_change_24h': -937486354.1419678, 'market_cap_change_percentage_24h': -1.03768, 'circulating_supply': 60917315351.0, 'total_supply': 99985721048.0, 'max_supply': 100000000000.0, 'ath': 3.65, 'ath_change_percentage': -59.74862, 'ath_date': '2025-07-18T03:40:53.808Z', 'atl': 0.00268621, 'atl_change_percentage': 54539.03509, 'atl_date': '2014-05-22T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-17T18:14:18.643Z'}
{'id': 'binancecoin', 'symbol': 'bnb', 'name': 'BNB', 'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970', 'current_price': 615.43, 'market_cap': 83746089453, 'market_cap_rank': 5, 'fully_diluted_valuation': 83746089152, 'total_volume': 796390913, 'high_24h': 630.22, 'low_24h': 610.02, 'price_change_24h': -1.4220735455402291, 'price_change_percentage_24h': -0.23054, 'market_cap_change_24h': -189299514.08518982, 'market_cap_change_percentage_24h': -0.22553, 'circulating_supply': 136359194.91, 'total_supply': 136359194.15, 'max_supply': 200000000.0, 'ath': 1369.99, 'ath_change_percentage': -55.07809, 'ath_date': '2025-10-13T08:41:24.131Z', 'atl': 0.0398177, 'atl_change_percentage': 1545510.12849, 'atl_date': '2017-10-19T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-17T18:14:12.934Z'}
{'id': 'usd-coin', 'symbol': 'usdc', 'name': 'USDC', 'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602', 'current_price': 0.9999, 'market_cap': 73570325921, 'market_cap_rank': 6, 'fully_diluted_valuation': 73578112706, 'total_volume': 4837077570, 'high_24h': 1.0, 'low_24h': 0.999797, 'price_change_24h': -7.0545835953117e-05, 'price_change_percentage_24h': -0.00705, 'market_cap_change_24h': -67821869.77789307, 'market_cap_change_percentage_24h': -0.0921, 'circulating_supply': 73571153941.07727, 'total_supply': 73403816891.6527, 'max_supply': None, 'ath': 1.17, 'ath_change_percentage': -14.72753, 'ath_date': '2019-05-08T00:40:28.300Z', 'atl': 0.877647, 'atl_change_percentage': 13.94056, 'atl_date': '2023-03-11T08:02:13.981Z', 'roi': None, 'last_updated': '2026-02-17T18:14:18.838Z'}
{'id': 'solana', 'symbol': 'sol', 'name': 'Solana', 'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756', 'current_price': 83.75, 'market_cap': 47488259251, 'market_cap_rank': 7, 'fully_diluted_valuation': 51872756462, 'total_volume': 3217296094, 'high_24h': 87.41, 'low_24h': 83.18, 'price_change_24h': -0.8424665534998894, 'price_change_percentage_24h': -0.99593, 'market_cap_change_24h': -490804863.5329666, 'market_cap_change_percentage_24h': -1.02296, 'circulating_supply': 568200534.8703105, 'total_supply': 620661368.3338143, 'max_supply': None, 'ath': 293.31, 'ath_change_percentage': -71.44735, 'ath_date': '2025-01-19T11:15:27.957Z', 'atl': 0.500801, 'atl_change_percentage': 16622.87141, 'atl_date': '2020-05-11T19:35:23.449Z', 'roi': None, 'last_updated': '2026-02-17T18:14:18.561Z'}
{'id': 'tron', 'symbol': 'trx', 'name': 'TRON', 'image': 'https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193', 'current_price': 0.280925, 'market_cap': 26574517349, 'market_cap_rank': 8, 'fully_diluted_valuation': 26574517089, 'total_volume': 611304951, 'high_24h': 0.285148, 'low_24h': 0.279834, 'price_change_24h': -0.002107284082860816, 'price_change_percentage_24h': -0.74454, 'market_cap_change_24h': -215049862.3384056, 'market_cap_change_percentage_24h': -0.80274, 'circulating_supply': 94726861319.1632, 'total_supply': 94726865175.7601, 'max_supply': None, 'ath': 0.431288, 'ath_change_percentage': -34.86383, 'ath_date': '2024-12-04T00:10:40.323Z', 'atl': 0.00180434, 'atl_change_percentage': 15469.37488, 'atl_date': '2017-11-12T00:00:00.000Z', 'roi': {'times': 146.85511218817194, 'currency': 'usd', 'percentage': 14685.511218817195}, 'last_updated': '2026-02-17T18:14:18.519Z'}
{'id': 'dogecoin', 'symbol': 'doge', 'name': 'Dogecoin', 'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409', 'current_price': 0.10065, 'market_cap': 16984366001, 'market_cap_rank': 9, 'fully_diluted_valuation': 16987198200, 'total_volume': 1051291940, 'high_24h': 0.102803, 'low_24h': 0.098644, 'price_change_24h': -0.000232943553598222, 'price_change_percentage_24h': -0.2309, 'market_cap_change_24h': -45859308.917850494, 'market_cap_change_percentage_24h': -0.26928, 'circulating_supply': 168752253126.579, 'total_supply': 168780583126.579, 'max_supply': None, 'ath': 0.731578, 'ath_change_percentage': -86.24208, 'ath_date': '2021-05-08T05:08:23.458Z', 'atl': 8.69e-05, 'atl_change_percentage': 115717.69759, 'atl_date': '2015-05-06T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-17T18:14:18.471Z'}
{'id': 'figure-heloc', 'symbol': 'figr_heloc', 'name': 'Figure Heloc', 'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954', 'current_price': 1.039, 'market_cap': 15754431192, 'market_cap_rank': 10, 'fully_diluted_valuation': 15754431192, 'total_volume': 7039905, 'high_24h': 1.04, 'low_24h': 1.013, 'price_change_24h': 0.0221221, 'price_change_percentage_24h': 2.17452, 'market_cap_change_24h': 296823909, 'market_cap_change_percentage_24h': 1.92024, 'circulating_supply': 15152324777.167, 'total_supply': 15152324777.167, 'max_supply': None, 'ath': 1.37, 'ath_change_percentage': -24.10555, 'ath_date': '2025-10-28T06:05:38.345Z', 'atl': 0.155357, 'atl_change_percentage': 569.0754, 'atl_date': '2025-10-31T14:27:24.456Z', 'roi': None, 'last_updated': '2026-02-17T18:14:18.194Z'}

In [ ]:
print(data[0])

{'id': 'bitcoin', 'symbol': 'btc', 'name': 'Bitcoin', 'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400', 'current_price': 67244, 'market_cap': 1344086585055, 'market_cap_rank': 1, 'fully_diluted_valuation': 1344092703480, 'total_volume': 37397635769, 'high_24h': 69088, 'low_24h': 66725, 'price_change_24h': -828.888136182577, 'price_change_percentage_24h': -1.21765, 'market_cap_change_24h': -16893524867.760254, 'market_cap_change_percentage_24h': -1.24128, 'circulating_supply': 19990746.0, 'total_supply': 19990837.0, 'max_supply': 21000000.0, 'ath': 126080, 'ath_change_percentage': -46.66546, 'ath_date': '2025-10-06T18:57:42.558Z', 'atl': 67.81, 'atl_change_percentage': 99066.97338, 'atl_date': '2013-07-06T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-17T18:14:13.021Z'}

**Перетворимо у DataFrame**

In [18]:
import pandas as pd

df = pd.DataFrame(data)

In [19]:
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,66536.000000,1334659979789,1,1334660778212,27560578385,66840.000000,...,2.005944e+07,2.100000e+07,126080.000000,-47.22721,2025-10-06T18:57:42.558Z,67.810000,9.802248e+04,2013-07-06T00:00:00.000Z,None,2026-07-21T16:36:26.499Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1924.390000,232240678776,2,232240678776,12100029155,1946.420000,...,1.206828e+08,NaN,4946.050000,-61.09227,2025-08-24T19:21:03.333Z,0.432979,4.443547e+05,2015-10-20T00:00:00.000Z,"{'times': 37.66975174871353, 'currency': 'btc'...",2026-07-21T16:36:26.464Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999381,184104706471,3,189568243299,48009305508,0.999442,...,1.896864e+11,NaN,1.320000,-24.46631,2018-07-24T00:00:00.000Z,0.572521,7.455827e+01,2015-03-02T00:00:00.000Z,None,2026-07-21T16:36:24.800Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,574.280000,76473728959,4,76473728218,624489647,578.990000,...,1.331659e+08,2.000000e+08,1369.990000,-58.08159,2025-10-13T08:41:24.131Z,0.039818,1.442170e+06,2017-10-19T00:00:00.000Z,None,2026-07-21T16:36:26.347Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999868,73236660731,5,73237654495,11854136647,0.999966,...,7.324732e+10,NaN,1.043000,-4.17628,2018-11-15T00:00:00.000Z,0.877647,1.392816e+01,2023-03-11T08:02:13.981Z,None,2026-07-21T16:36:11.883Z
5,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.150000,71830507807,6,114973927577,1363496827,1.150000,...,9.998564e+10,1.000000e+11,3.650000,-68.46448,2025-07-18T03:40:53.808Z,0.002686,4.270774e+04,2014-05-22T00:00:00.000Z,None,2026-07-21T16:36:08.333Z
6,solana,sol,Solana,https://coin-images.coingecko.com/coins/images...,78.020000,45454744209,7,49198090408,1702246514,78.640000,...,6.307406e+08,NaN,293.310000,-73.40198,2025-01-19T11:15:27.957Z,0.500801,1.547807e+04,2020-05-11T19:35:23.449Z,None,2026-07-21T16:36:27.072Z
7,tron,trx,TRON,https://coin-images.coingecko.com/coins/images...,0.328654,31181056758,8,31181056439,332693093,0.328705,...,9.487512e+10,NaN,0.431288,-23.79723,2024-12-04T00:10:40.323Z,0.001804,1.811460e+04,2017-11-12T00:00:00.000Z,"{'times': 171.97561504374332, 'currency': 'usd...",2026-07-21T16:36:18.821Z
8,figure-heloc,figr_heloc,Figure Heloc,https://coin-images.coingecko.com/coins/images...,1.001000,20220814989,9,20220814989,28774758,1.008000,...,2.020535e+10,NaN,1.049000,-4.60895,2026-03-09T17:00:25.937Z,0.155357,5.441730e+02,2025-10-31T14:27:24.456Z,None,2026-07-21T16:36:13.087Z
9,hyperliquid,hype,Hyperliquid,https://coin-images.coingecko.com/coins/images...,61.540000,13689048838,10,58788479339,330327665,63.300000,...,9.553071e+08,1.000000e+09,76.700000,-19.76417,2026-06-16T13:02:04.375Z,3.810000,1.515845e+03,2024-11-29T09:30:30.871Z,None,2026-07-21T16:36:08.800Z

In [20]:
df[['id', 'symbol', 'current_price', 'market_cap', 'price_change_percentage_24h']]

,id,symbol,current_price,market_cap,price_change_percentage_24h
0,bitcoin,btc,66536.000000,1334659979789,1.74732
1,ethereum,eth,1924.390000,232240678776,1.31427
2,tether,usdt,0.999381,184104706471,0.03037
3,binancecoin,bnb,574.280000,76473728959,0.22409
4,usd-coin,usdc,0.999868,73236660731,0.00957
5,ripple,xrp,1.150000,71830507807,3.48494
6,solana,sol,78.020000,45454744209,0.57058
7,tron,trx,0.328654,31181056758,0.82050
8,figure-heloc,figr_heloc,1.001000,20220814989,-0.72173
9,hyperliquid,hype,61.540000,13689048838,-0.96974

In [21]:
df = pd.read_json('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=500')
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,66576.000000,1335153017028,1,1335153815746,3.067941e+10,66840.000000,...,2.005944e+07,2.100000e+07,126080.000,-47.19548,2025-10-06T18:57:42.558Z,67.810000,9.808149e+04,2013-07-06T00:00:00.000Z,None,2026-07-21T16:38:42.386Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1924.520000,232226053394,2,232226053394,1.187602e+10,1946.420000,...,1.206828e+08,NaN,4946.050,-61.08979,2025-08-24T19:21:03.333Z,0.432979,4.443831e+05,2015-10-20T00:00:00.000Z,"{'times': 37.65561270133281, 'currency': 'btc'...",2026-07-21T16:38:41.006Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999380,184105123127,3,189568672320,4.799816e+10,0.999442,...,1.896864e+11,NaN,1.320,-24.46631,2018-07-24T00:00:00.000Z,0.572521,7.455827e+01,2015-03-02T00:00:00.000Z,None,2026-07-21T16:38:29.985Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,574.230000,76469251653,4,76469250912,6.149358e+08,578.990000,...,1.331659e+08,2.000000e+08,1369.990,-58.08484,2025-10-13T08:41:24.131Z,0.039818,1.442058e+06,2017-10-19T00:00:00.000Z,None,2026-07-21T16:38:41.725Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999867,73237733341,5,73238727120,1.183782e+10,0.999966,...,7.324732e+10,NaN,1.043,-4.17628,2018-11-15T00:00:00.000Z,0.877647,1.392816e+01,2023-03-11T08:02:13.981Z,None,2026-07-21T16:38:37.181Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,lighter,lit,Lighter,https://coin-images.coingecko.com/coins/images...,2.290000,573401127,95,2293604509,3.667376e+07,2.380000,...,1.000000e+09,1.000000e+09,7.860,-70.57281,2025-12-30T09:05:21.222Z,0.780945,1.961692e+02,2026-03-31T10:05:09.239Z,None,2026-07-21T16:38:40.985Z
96,ylds,ylds,YLDS,https://coin-images.coingecko.com/coins/images...,0.999937,563732849,97,563732849,1.001300e+07,0.999949,...,5.637686e+08,NaN,1.001,-0.11472,2026-02-13T15:00:58.249Z,0.999202,7.354000e-02,2025-11-16T12:26:29.488Z,None,2026-07-21T16:38:37.222Z
97,usual-usd,usd0,Usual USD,https://coin-images.coingecko.com/coins/images...,0.999344,552813021,98,552813021,1.205556e+06,0.999433,...,5.531759e+08,NaN,1.330,-24.61765,2024-07-12T08:28:59.311Z,0.962885,3.786390e+00,2025-04-10T08:30:51.088Z,None,2026-07-21T16:38:43.082Z
98,injective-protocol,inj,Injective,https://coin-images.coingecko.com/coins/images...,5.300000,530368252,99,530368252,7.794210e+07,5.460000,...,1.000000e+08,NaN,52.620,-89.93411,2024-03-14T15:06:22.124Z,0.657401,7.057095e+02,2020-11-03T16:19:30.576Z,None,2026-07-21T16:38:25.513Z
99,usx,usx,USX,https://coin-images.coingecko.com/coins/images...,0.999863,522918487,100,522918487,1.145196e+06,1.000000,...,5.229883e+08,NaN,1.170,-14.84796,2026-07-14T11:50:40.475Z,0.828472,2.069317e+01,2025-12-26T04:30:55.143Z,None,2026-07-21T16:38:38.668Z

# Робота з API з авторизацією (CoinMarketCap)

## Реєстрація та отримання ключа

* Зареєструйтесь на [CoinMarketCap](https://coinmarketcap.com/api/)
* Після реєстрації отримаєте `X-CMC_PRO_API_KEY`

## Приклад документації:

* Документація: [https://coinmarketcap.com/api/documentation/v1/](https://coinmarketcap.com/api/documentation/v1/)
* Endpoint: `/v1/cryptocurrency/listings/latest`

## Приклад запиту з ключем

In [22]:
url = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest"
headers = {
    "Accepts": "application/json",
    "X-CMC_PRO_API_KEY": "17ad748a-f734-46e1-8ae0-16044d2215b8"
}
params = {
    "start": "1",
    "limit": "30",
    "convert": "USD"
}

response = requests.get(url, headers=headers, params=params)
data = response.json()

In [25]:
data

{'data': [{'id': 1,
   'name': 'Bitcoin',
   'symbol': 'BTC',
   'slug': 'bitcoin',
   'infinite_supply': False,
   'circulating_supply': 20059440,
   'total_supply': 20059440,
   'max_supply': 21000000,
   'date_added': '2010-07-13T00:00:00.000Z',
   'num_market_pairs': 12670,
   'cmc_rank': 1,
   'last_updated': '2026-07-21T16:46:00.000Z',
   'tvl_ratio': None,
   'platform': None,
   'self_reported_circulating_supply': None,
   'self_reported_market_cap': None,
   'minted_market_cap': 1333694473615.97,
   'quote': {'USD': {'price': 66487.12394842395,
     'volume_24h': 29568977442.137226,
     'cex_volume_24h': 29535135905.007465,
     'dex_volume_24h': 33841537.12975644,
     'volume_change_24h': 4.4558,
     'percent_change_1h': -0.12544083,
     'percent_change_24h': 1.71275886,
     'percent_change_7d': 2.70759036,
     'percent_change_30d': 3.75942942,
     'percent_change_60d': -13.5092804,
     'percent_change_90d': -15.60037747,
     'market_cap': 1333694473615.9734,
     'market_cap_dominance': 58.945,
     'fully_diluted_market_cap': 1396229602916.9,
     'tvl': None,
     'last_updated': '2026-07-21T16:46:00.000Z'}},
   'tags': ['mineable',
    'pow',
    'sha-256',
    'store-of-value',
    'state-channel',
    'coinbase-ventures-portfolio',
    'three-arrows-capital-portfolio',
    'polychain-capital-portfolio',
    'binance-labs-portfolio',
    'blockchain-capital-portfolio',
    'boostvc-portfolio',
    'cms-holdings-portfolio',
    'dcg-portfolio',
    'dragonfly-capital-portfolio',
    'electric-capital-portfolio',
    'fabric-ventures-portfolio',
    'framework-ventures-portfolio',
    'galaxy-digital-portfolio',
    'huobi-capital-portfolio',
    'alameda-research-portfolio',
    'a16z-portfolio',
    '1confirmation-portfolio',
    'winklevoss-capital-portfolio',
    'usv-portfolio',
    'placeholder-ventures-portfolio',
    'pantera-capital-portfolio',
    'multicoin-capital-portfolio',
    'paradigm-portfolio',
    'bitcoin-ecosystem',
    'layer-1',
    'ftx-bankruptcy-estate',
    '2017-2018-alt-season',
    'us-strategic-crypto-reserve',
    'binance-ecosystem',
    'binance-listing',
    'sec-cftc-token-taxonomy',
    'sec-cftc-digital-commodities']},
  {'id': 1027,
   'name': 'Ethereum',
   'symbol': 'ETH',
   'slug': 'ethereum',
   'infinite_supply': True,
   'circulating_supply': 120682803.07559188,
   'total_supply': 120682803.07559188,
   'max_supply': None,
   'date_added': '2015-08-07T00:00:00.000Z',
   'num_market_pairs': 12210,
   'cmc_rank': 2,
   'last_updated': '2026-07-21T16:46:00.000Z',
   'tvl_ratio': None,
   'platform': None,
   'self_reported_circulating_supply': None,
   'self_reported_market_cap': None,
   'minted_market_cap': 232023941832.58,
   'quote': {'USD': {'price': 1922.5932437718477,
     'volume_24h': 12747305554.491896,
     'cex_volume_24h': 12655538970.295305,
     'dex_volume_24h': 91766584.19659579,
     'volume_change_24h': 13.7108,
     'percent_change_1h': -0.1700374,
     'percent_change_24h': 1.35821756,
     'percent_change_7d': 2.68478711,
     'percent_change_30d': 11.4359253,
     'percent_change_60d': -9.29085216,
     'percent_change_90d': -19.52008758,
     'market_cap': 232023941832.5813,
     'market_cap_dominance': 10.2547,
     'fully_diluted_market_cap': 232023941832.58,
     'tvl': None,
     'last_updated': '2026-07-21T16:46:00.000Z'}},
   'tags': ['pos',
    'smart-contracts',
    'ethereum-ecosystem',
    'coinbase-ventures-portfolio',
    'three-arrows-capital-portfolio',
    'polychain-capital-portfolio',
    'binance-labs-portfolio',
    'blockchain-capital-portfolio',
    'boostvc-portfolio',
    'cms-holdings-portfolio',
    'dcg-portfolio',
    'dragonfly-capital-portfolio',
    'electric-capital-portfolio',
    'fabric-ventures-portfolio',
    'framework-ventures-portfolio',
    'hashkey-capital-portfolio',
    'kenetic-capital-portfolio',
    'huobi-capital-portfolio',
    'alameda-research-portfolio',
    'a16z-portfolio',
    '1confirmation-portfolio',
    'winklevoss-capital-portfolio',
    'usv-portfolio',
    'placeholder-ventures-portfolio',
    'pantera-capital-portfolio',
    'multicoin-capital-portfolio',
    'paradigm-portfolio',
    'ethereum-pow-ecosystem',
    'layer-1',
    'ftx-bankruptcy-estate',
    'sora-ecosystem',
    'rsk-rbtc-ecosystem',
    'world-liberty-financial-portfolio',
    'us-strategic-crypto-reserve',
    'binance-ecosystem',
    'binance-listing',
    'abstract-chain-ecosystem',
    'unichain-ecosystem',
    'soneium-ecosystem',
    'sophon-ecosystem',
    'sec-cftc-token-taxonomy',
    'sec-cftc-digital-commodities',
    'anubis-ecosystem',
    'robinhood-ecosystem']},
  {'id': 825,
   'name': 'Tether USDt',
   'symbol': 'USDT',
   'slug': 'tether',
   'infinite_supply': True,
   'circulating_supply': 184219443473.5799,
   'total_supply': 189112591385.27026,
   'max_supply': None,
   'date_added': '2015-02-25T00:00:00.000Z',
   'num_market_pairs': 190777,
   'cmc_rank': 3,
   'last_updated': '2026-07-21T16:45:00.000Z',
   'tvl_ratio': None,
   'platform': {'id': 1027,
    'slug': 'ethereum',
    'name': 'Ethereum',
    'symbol': 'ETH',
    'token_address': '0xdac17f958d2ee523a2206206994597c13d831ec7'},
   'self_reported_circulating_supply': None,
   'self_reported_market_cap': None,
   'minted_market_cap': 189005593801.15,
   'quote': {'USD': {'price': 0.9994342122682723,
     'volume_24h': 60358514483.77831,
     'cex_volume_24h': 59125993293.39941,
     'dex_volume_24h': 1232521190.3789246,
     'volume_change_24h': 9.2403,
     'percent_change_1h': -0.01434979,
     'percent_change_24h': 0.02999017,
     'percent_change_7d': 0.01124163,
     'percent_change_30d': 0.05867525,
     'percent_change_60d': 0.04989957,
     'percent_change_90d': -0.06557177,
     'market_cap': 184115214372.51685,
     'market_cap_dominance': 8.1373,
     'fully_diluted_market_cap': 189005593801.15,
     'tvl': None,
     'last_updated': '2026-07-21T16:45:00.000Z'}},
   'tags': ['stablecoin',
    'asset-backed-stablecoin',
    'usd-stablecoin',
    'ethereum-pow-ecosystem',
    'fiat-stablecoin',
    'tron20-ecosystem',
    'rsk-rbtc-ecosystem',
    'venom-ecosystem',
    'world-liberty-financial-portfolio',
    'binance-ecosystem',
    'binance-listing',
    'peaq-ecosystem',
    'etherlink-ecosystem',
    'duckchain-ecosystem',
    'onus-ecosystem',
    'sophon-ecosystem',
    'xlayer-ecosystem']},
  {'id': 1839,
   'name': 'BNB',
   'symbol': 'BNB',
   'slug': 'bnb',
   'infinite_supply': False,
   'circulating_supply': 133165882.18,
   'total_supply': 133165882.18,
   'max_supply': 133165882.95,
   'date_added': '2017-07-25T00:00:00.000Z',
   'num_market_pairs': 3305,
   'cmc_rank': 4,
   'last_updated': '2026-07-21T16:46:00.000Z',
   'tvl_ratio': None,
   'platform': None,
   'self_reported_circulating_supply': None,
   'self_reported_market_cap': None,
   'minted_market_cap': 76472234307.98,
   'quote': {'USD': {'price': 574.2629647781255,
     'volume_24h': 1135220643.8551874,
     'cex_volume_24h': 1112019651.4877217,
     'dex_volume_24h': 23200992.36746547,
     'volume_change_24h': 6.9427,
     'percent_change_1h': -0.08377051,
     'percent_change_24h': 0.3096075,
     'percent_change_7d': -1.29360679,
     'percent_change_30d': -2.45898852,
     'percent_change_60d': -12.8114613,
     'percent_change_90d': -11.2142232,
     'market_cap': 76472234307.98135,
     'market_cap_dominance': 3.3798,
     'fully_diluted_market_cap': 76472234750.16,
     'tvl': None,
     'last_updated': '2026-07-21T16:46:00.000Z'}},
   'tags': ['marketplace',
    'centralized-exchange',
    'payments',
    'smart-contracts',
    'alameda-research-portfolio',
    'multicoin-capital-portfolio',
    'bnb-chain-ecosystem',
    'layer-1',
    'alleged-sec-securities',
    'celsius-bankruptcy-estate',
    'binance-ecosystem',
    'binance-listing',
    'etherlink-ecosystem',
    'made-in-china']},
  {'id': 3408,
   'name': 'USDC',
   'symbol': 'USDC',
   'slug': 'usd-coin',
   'infinite_supply': False,
   'circulating_supply': 73247323041.8707,
   'total_supply': 73247323041.8707,
   'max_supply': None,
   'date_added': '2018-10-08T00:00:00.000Z',
   'num_market_pairs': 41765,
   'cmc_rank': 5,
   'last_updated': '2026-07-21T16:46:00.000Z',
   'tvl_ratio': None,
   'platform': {'id': 1027,
    'slug': 'ethereum',
    'name': 'Ethereum',
    'symbol': 'ETH',
    'token_address': '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'},
   'self_reported_circulating_supply': 60901219650.23,
   'self_reported_market_cap': 60902146007.585815,
   'minted_market_cap': 73248437193.56,
   'quote': {'USD': {'price': 1.0000152108177986,
     'volume_24h': 10058277879.022518,
     'cex_volume_24h': 8717535517.288319,
     'dex_volume_24h': 1340742361.7341723,
     'volume_change_24h': 1.8319,
     'percent_change_1h': 0.0131577,
     'percent_change_24h': 0.00981347,
     'percent_change_7d': 0.01896273,
     'percent_change_30d': 0.01619393,
     'percent_change_60d': 0.02779333,
     'percent_change_90d': 0.03515515,
     'market_cap': 73248437193.55573,
     'market_cap_dominance': 3.2373,
     'fully_diluted_market_cap': 73248437193.56,
     'tvl': None,
     'last_updated': '2026-07-21T16:46:00.000Z'}},
   'tags': ['medium-of-exchange',
    'stablecoin',
    'asset-backed-stablecoin',
    'stellar-ecosystem',
    'coinbase-ventures-portfolio',
    'usd-stablecoin',
    'xdc-ecosystem',
    'ethereum-pow-ecosystem',
    'fiat-stablecoin',
    'tron20-ecosystem',
    'venom-ecosystem',
    'made-in-america',
    'world-liberty-financial-portfolio',
    'sonic-ecosystem',
    'binance-ecosystem',
    'binance-listing',
    'hyperevm-ecosystem',
    'etherlink-ecosystem',
    'unichain-ecosystem',
    'vector-smart-chain-ecosystem',
    'sophon-ecosystem',
    'monad-ecosystem',
    'xlayer-ecosystem']},
  {'id': 52,
   'name': 'XRP',
   'symbol': 'XRP',
   'slug': 'xrp',
   'infinite_supply': False,
   'circulating_supply': 62466503703,
   'total_supply': 99985639695,
   'max_supply': 100000000000,
   'date_added': '2013-08-04T00:00:00.000Z',
   'num_market_pairs': 1849,
   'cmc_rank': 6,
   'last_updated': '2026-07-21T16:45:00.000Z',
   'tvl_ratio': None,
   'platform': None,
   'self_reported_circulating_supply': None,
   'self_reported_market_cap': None,
   'minted_market_cap': 114959053178.76,
   'quote': {'USD': {'price': 1.1497556402042721,
     'volume_24h': 1421745768.4572835,
     'cex_volume_24h': 1420888687.6130698,
     'dex_volume_24h': 857080.84421327,
     'volume_change_24h': 28.7052,
     'percent_change_1h': 0.14109856,
     'percent_change_24h': 3.47948794,
     'percent_change_7d': 3.94313236,
     'percent_change_30d': 0.60972202,
     'percent_change_60d': -14.89034629,
     'percent_change_90d': -20.60166317,
     'market_cap': 71821214956.3653,
     'market_cap_dominance': 3.1743,
     'fully_diluted_market_cap': 114975564020.43,
     'tvl': None,
     'last_updated': '2026-07-21T16:45:00.000Z'}},
   'tags': ['medium-of-exchange',
    'enterprise-solutions',
    'xrp-ecosystem',
    'solana-ecosystem',
    'arrington-xrp-capital-portfolio',
    'galaxy-digital-portfolio',
    'a16z-portfolio',
    'pantera-capital-portfolio',
    'ftx-bankruptcy-estate',
    '2017-2018-alt-season',
    'klaytn-ecosystem',
    'made-in-america',
    'us-strategic-crypto-reserve',
    'binance-ecosystem',
    'binance-listing',
    'iso-20022',
    'sec-cftc-token-taxonomy',
    'sec-cftc-digital-commodities']},
  {'id': 5426,
   'name': 'Solana',
   'symbol': 'SOL',
   'slug': 'solana',
   'infinite_supply': True,
   'circulating_supply': 582749333.4592701,
   'total_supply': 630740640.2820572,
   'max_supply': None,
   'date_added': '2020-04-10T00:00:00.000Z',
   'num_market_pairs': 1147,
   'cmc_rank': 7,
   'last_updated': '2026-07-21T16:45:00.000Z',
   'tvl_ratio': None,
   'platform': None,
   'self_reported_circulating_supply': 525236893.3,
   'self_reported_market_cap': 41013645726.74934,
   'minted_market_cap': 49252010846.88,
   'quote': {'USD': {'price': 78.08599557633042,
     'volume_24h': 1777512419.960628,
     'cex_volume_24h': 1777491005.9092917,
     'dex_volume_24h': 21414.05133652,
     'volume_change_24h': -12.1574,
     'percent_change_1h': 0.14354252,
     'percent_change_24h': 0.69747521,
     'percent_change_7d': 0.85065189,
     'percent_change_30d': 5.58390358,
     'percent_change_60d': -9.956716,
     'percent_change_90d': -11.09975432,
     'market_cap': 45504561874.61007,
     'market_cap_dominance': 2.0112,
     'fully_diluted_market_cap': 49252010846.88,
     'tvl': None,
     'last_updated': '2026-07-21T16:45:00.000Z'}},
   'tags': ['pos',
    'platform',
    'solana-ecosystem',
    'cms-holdings-portfolio',
    'kenetic-capital-portfolio',
    'alameda-research-portfolio',
    'multicoin-capital-portfolio',
    'okx-ventures-portfolio',
    'layer-1',
    'ftx-bankruptcy-estate',
    'alleged-sec-securities',
    'cmc-crypto-awards-2024',
    'made-in-america',
    'us-strategic-crypto-reserve',
    'binance-ecosystem',
    'binance-listing',
    'sec-cftc-token-taxonomy',
    'sec-cftc-digital-commodities',
    'coinlist-launchpad']},
  {'id': 1958,
   'name': 'TRON',
   'symbol': 'TRX',
   'slug': 'tron',
   'infinite_supply': True,
   'circulating_supply': 94875121400.0912,
   'total_supply': 94875122213.2912,
   'max_supply': None,
   'date_added': '2017-09-13T00:00:00.000Z',
   'num_market_pairs': 1351,
   'cmc_rank': 8,
   'last_updated': '2026-07-21T16:46:00.000Z',
   'tvl_ratio': None,
   'platform': None,
   'self_reported_circulating_supply': 94667886298.43,
   'self_reported_market_cap': 31109751513.35065,
   'minted_market_cap': 31177853359.37,
   'quote': {'USD': {'price': 0.32861990195155105,
     'volume_24h': 407355067.9873989,
     'cex_volume_24h': 407310945.1066333,
     'dex_volume_24h': 44122.88076561,
     'volume_change_24h': -0.1392,
     'percent_change_1h': 0.07026573,
     'percent_change_24h': 0.83223955,
     'percent_change_7d': 1.16654554,
     'percent_change_30d': 0.61499966,
     'percent_change_60d': -9.35053665,
     'percent_change_90d': -0.06009984,
     'market_cap': 31177853092.139473,
     'market_cap_dominance': 1.378,
     'fully_diluted_market_cap': 31177853359.37,
     'tvl': None,
     'last_updated': '2026-07-21T16:46:00.000Z'}},
   'tags': ['media',
    'payments',
    'tron-ecosystem',
    'layer-1',
    'dwf-labs-portfolio',
    'alleged-sec-securities',
    '2017-2018-alt-season',
    'tron20-ecosystem',
    'world-liberty-financial-portfolio',
    'binance-ecosystem',
    'binance-listing',
    'made-in-china']},
  {'id': 32196,
   'name': 'Hyperliquid',
   'symbol': 'HYPE',
   'slug': 'hyperliquid',
   'infinite_supply': False,
   'circulating_supply': 252817496.96782613,
   'total_supply': 953149360.6187525,
   'max_supply': 953149975.4690608,
   'date_added': '2024-07-15T10:14:50.000Z',
   'num_market_pairs': 291,
   'cmc_rank': 9,
   'last_updated': '2026-07-21T16:46:00.000Z',
   'tvl_ratio': None,
   'platform': {'id': 32196,
    'slug': 'hyperliquid',
    'name': 'Hyperliquid',
    'symbol': 'HYPE',
    'token_address': '0x0d01dc56dcaaca66ad901c959b4011ec'},
   'self_reported_circulating_supply': 333931719,
   'self_reported_market_cap': 20631606064.87523,
   'minted_market_cap': 58889290865.1,
   'quote': {'USD': {'price': 61.783906382595625,
     'volume_24h': 302679337.27677286,
     'cex_volume_24h': 260926169.67188114,
     'dex_volume_24h': 41753167.60489164,
     'volume_change_24h': 3.2718,
     'percent_change_1h': 0.28020417,
     'percent_change_24h': -0.55955783,
     'percent_change_7d': -4.75450322,
     'percent_change_30d': -9.1121595,
     'percent_change_60d': 7.13722234,
     'percent_change_90d': 50.55423977,
     'market_cap': 15620052564.542324,
     'market_cap_dominance': 0.6904,
     'fully_diluted_market_cap': 58889328852.95,
     'tvl': None,
     'last_updated': '2026-07-21T16:46:00.000Z'}},
   'tags': ['decentralized-exchange-dex-token',
    'defi',
    'derivatives',
    'layer-1',
    'hyperliquid-ecosystem',
    'binance-ecosystem',
    'binance-listing',
    'perpetuals']},
  {'id': 74,
   'name': 'Dogecoin',
   'symbol': 'DOGE',
   'slug': 'dogecoin',
   'infinite_supply': True,
   'circulating_supply': 170876023126.57907,
   'total_supply': 170876023126.57907,
   'max_supply': None,
   'date_added': '2013-12-15T00:00:00.000Z',
   'num_market_pairs': 1454,
   'cmc_rank': 10,
   'last_updated': '2026-07-21T16:45:00.000Z',
   'tvl_ratio': None,
   'platform': None,
   'self_reported_circulating_supply': None,
   'self_reported_market_cap': None,
   'minted_market_cap': 12530213978,
   'quote': {'USD': {'price': 0.07332926965838071,
     'volume_24h': 688264883.4796077,
     'cex_volume_24h': 687950248.0135939,
     'dex_volume_24h': 314635.46601369,
     'volume_change_24h': 24.178,
     'percent_change_1h': 0.17741567,
     'percent_change_24h': 0.35899884,
     'percent_change_7d': -1.89702716,
     'percent_change_30d': -11.86699271,
     'percent_change_60d': -30.61150278,
     'percent_change_90d': -24.68329067,
     'market_cap': 12530213978.000616,
     'market_cap_dominance': 0.5538,
     'fully_diluted_market_cap': 12530213978,
     'tvl': None,
     'last_updated': '2026-07-21T16:45:00.000Z'}},
   'tags': ['mineable',
    'pow',
    'scrypt',
    'medium-of-exchange',
    'memes',
    'payments',
    'doggone-doggerel',
    'doge-chain-ecosystem',
    'osmosis-ecosystem',
    'ftx-bankruptcy-estate',
    'animal-memes',
    'made-in-america',
    'binance-ecosystem',
    'binance-listing',
    'sec-cftc-token-taxonomy',
    'sec-cftc-digital-commodities']},
  {'id': 1437,
   'name': 'Zcash',
   'symbol': 'ZEC',
   'slug': 'zcash',
   'infinite_supply': False,
   'circulating_supply': 16782403.1655448,
   'total_supply': 16782403.1655448,
   'max_supply': 21000000,
   'date_added': '2016-10-29T00:00:00.000Z',
   'num_market_pairs': 628,
   'cmc_rank': 11,
   'last_updated': '2026-07-21T16:45:00.000Z',
   'tvl_ratio': None,
   'platform': None,
   'self_reported_circulating_supply': None,
   'self_reported_market_cap': None,
   'minted_market_cap': 9035707035.79,
   'quote': {'USD': {'price': 538.4036449760889,
     'volume_24h': 472294270.104434,
     'cex_volume_24h': 445640500.08427805,
     'dex_volume_24h': 26653770.02015604,
     'volume_change_24h': -1.0595,
     'percent_change_1h': -0.29518861,
     'percent_change_24h': -2.21766339,
     'percent_change_7d': -1.07526923,
     'percent_change_30d': 20.14412505,
     'percent_change_60d': -13.75006702,
     'percent_change_90d': 66.01626841,
     'market_cap': 9035707035.787573,
     'market_cap_dominance': 0.3993,
     'fully_diluted_market_cap': 11306476544.5,
     'tvl': None,
     'last_updated': '2026-07-21T16:45:00.000Z'}},
   'tags': ['mineable',
    'pow',
    'equihash',
    'medium-of-exchange',
    'privacy',
    'zero-knowledge-proofs',
    'quantum-resistant',
    'binance-chain',
    'boostvc-portfolio',
    'dcg-portfolio',
    'electric-capital-portfolio',
    'fenbushi-capital-portfolio',
    'hashkey-capital-portfolio',
    'winklevoss-capital-portfolio',
    'placeholder-ventures-portfolio',
    'pantera-capital-portfolio',
    'layer-1',
    'standard-crypto-portfolio',
    '2017-2018-alt-season',
    'made-in-america',
    'binance-ecosystem',
    'binance-listing',
    'privacy-coins']},
  {'id': 3957,
   'name': 'UNUS SED LEO',
   'symbol': 'LEO',
   'slug': 'unus-sed-leo',
   'infinite_supply': False,
   'circulating_supply': 920152521.9,
   'total_supply': 985239504,
   'max_supply': None,
   'date_added': '2019-05-21T00:00:00.000Z',
   'num_market_pairs': 69,
   'cmc_rank': 12,
   'last_updated': '2026-07-21T16:46:00.000Z',
   'tvl_ratio': None,
   'platform': {'id': 1027,
    'slug': 'ethereum',
    'name': 'Ethereum',
    'symbol': 'ETH',
    'token_address': '0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3'},

In [23]:
response.status_code

200

In [ ]:
data.keys()

dict_keys(['status', 'data'])

In [24]:
data.keys()

dict_keys(['data', 'status'])

In [26]:
data['status']

{'timestamp': '2026-07-21T16:47:18.626Z',
 'error_code': 0,
 'error_message': None,
 'elapsed': 13,
 'credit_count': 1,
 'total_count': 8121,
 'notice': None}

In [27]:
data['data']

[{'id': 1,
  'name': 'Bitcoin',
  'symbol': 'BTC',
  'slug': 'bitcoin',
  'infinite_supply': False,
  'circulating_supply': 20059440,
  'total_supply': 20059440,
  'max_supply': 21000000,
  'date_added': '2010-07-13T00:00:00.000Z',
  'num_market_pairs': 12670,
  'cmc_rank': 1,
  'last_updated': '2026-07-21T16:46:00.000Z',
  'tvl_ratio': None,
  'platform': None,
  'self_reported_circulating_supply': None,
  'self_reported_market_cap': None,
  'minted_market_cap': 1333694473615.97,
  'quote': {'USD': {'price': 66487.12394842395,
    'volume_24h': 29568977442.137226,
    'cex_volume_24h': 29535135905.007465,
    'dex_volume_24h': 33841537.12975644,
    'volume_change_24h': 4.4558,
    'percent_change_1h': -0.12544083,
    'percent_change_24h': 1.71275886,
    'percent_change_7d': 2.70759036,
    'percent_change_30d': 3.75942942,
    'percent_change_60d': -13.5092804,
    'percent_change_90d': -15.60037747,
    'market_cap': 1333694473615.9734,
    'market_cap_dominance': 58.945,
    'fully_diluted_market_cap': 1396229602916.9,
    'tvl': None,
    'last_updated': '2026-07-21T16:46:00.000Z'}},
  'tags': ['mineable',
   'pow',
   'sha-256',
   'store-of-value',
   'state-channel',
   'coinbase-ventures-portfolio',
   'three-arrows-capital-portfolio',
   'polychain-capital-portfolio',
   'binance-labs-portfolio',
   'blockchain-capital-portfolio',
   'boostvc-portfolio',
   'cms-holdings-portfolio',
   'dcg-portfolio',
   'dragonfly-capital-portfolio',
   'electric-capital-portfolio',
   'fabric-ventures-portfolio',
   'framework-ventures-portfolio',
   'galaxy-digital-portfolio',
   'huobi-capital-portfolio',
   'alameda-research-portfolio',
   'a16z-portfolio',
   '1confirmation-portfolio',
   'winklevoss-capital-portfolio',
   'usv-portfolio',
   'placeholder-ventures-portfolio',
   'pantera-capital-portfolio',
   'multicoin-capital-portfolio',
   'paradigm-portfolio',
   'bitcoin-ecosystem',
   'layer-1',
   'ftx-bankruptcy-estate',
   '2017-2018-alt-season',
   'us-strategic-crypto-reserve',
   'binance-ecosystem',
   'binance-listing',
   'sec-cftc-token-taxonomy',
   'sec-cftc-digital-commodities']},
 {'id': 1027,
  'name': 'Ethereum',
  'symbol': 'ETH',
  'slug': 'ethereum',
  'infinite_supply': True,
  'circulating_supply': 120682803.07559188,
  'total_supply': 120682803.07559188,
  'max_supply': None,
  'date_added': '2015-08-07T00:00:00.000Z',
  'num_market_pairs': 12210,
  'cmc_rank': 2,
  'last_updated': '2026-07-21T16:46:00.000Z',
  'tvl_ratio': None,
  'platform': None,
  'self_reported_circulating_supply': None,
  'self_reported_market_cap': None,
  'minted_market_cap': 232023941832.58,
  'quote': {'USD': {'price': 1922.5932437718477,
    'volume_24h': 12747305554.491896,
    'cex_volume_24h': 12655538970.295305,
    'dex_volume_24h': 91766584.19659579,
    'volume_change_24h': 13.7108,
    'percent_change_1h': -0.1700374,
    'percent_change_24h': 1.35821756,
    'percent_change_7d': 2.68478711,
    'percent_change_30d': 11.4359253,
    'percent_change_60d': -9.29085216,
    'percent_change_90d': -19.52008758,
    'market_cap': 232023941832.5813,
    'market_cap_dominance': 10.2547,
    'fully_diluted_market_cap': 232023941832.58,
    'tvl': None,
    'last_updated': '2026-07-21T16:46:00.000Z'}},
  'tags': ['pos',
   'smart-contracts',
   'ethereum-ecosystem',
   'coinbase-ventures-portfolio',
   'three-arrows-capital-portfolio',
   'polychain-capital-portfolio',
   'binance-labs-portfolio',
   'blockchain-capital-portfolio',
   'boostvc-portfolio',
   'cms-holdings-portfolio',
   'dcg-portfolio',
   'dragonfly-capital-portfolio',
   'electric-capital-portfolio',
   'fabric-ventures-portfolio',
   'framework-ventures-portfolio',
   'hashkey-capital-portfolio',
   'kenetic-capital-portfolio',
   'huobi-capital-portfolio',
   'alameda-research-portfolio',
   'a16z-portfolio',
   '1confirmation-portfolio',
   'winklevoss-capital-portfolio',
   'usv-portfolio',
   'placeholder-ventures-portfolio',
   'pantera-capital-portfolio',
   'multicoin-capital-portfolio',
   'paradigm-portfolio',
   'ethereum-pow-ecosystem',
   'layer-1',
   'ftx-bankruptcy-estate',
   'sora-ecosystem',
   'rsk-rbtc-ecosystem',
   'world-liberty-financial-portfolio',
   'us-strategic-crypto-reserve',
   'binance-ecosystem',
   'binance-listing',
   'abstract-chain-ecosystem',
   'unichain-ecosystem',
   'soneium-ecosystem',
   'sophon-ecosystem',
   'sec-cftc-token-taxonomy',
   'sec-cftc-digital-commodities',
   'anubis-ecosystem',
   'robinhood-ecosystem']},
 {'id': 825,
  'name': 'Tether USDt',
  'symbol': 'USDT',
  'slug': 'tether',
  'infinite_supply': True,
  'circulating_supply': 184219443473.5799,
  'total_supply': 189112591385.27026,
  'max_supply': None,
  'date_added': '2015-02-25T00:00:00.000Z',
  'num_market_pairs': 190777,
  'cmc_rank': 3,
  'last_updated': '2026-07-21T16:45:00.000Z',
  'tvl_ratio': None,
  'platform': {'id': 1027,
   'slug': 'ethereum',
   'name': 'Ethereum',
   'symbol': 'ETH',
   'token_address': '0xdac17f958d2ee523a2206206994597c13d831ec7'},
  'self_reported_circulating_supply': None,
  'self_reported_market_cap': None,
  'minted_market_cap': 189005593801.15,
  'quote': {'USD': {'price': 0.9994342122682723,
    'volume_24h': 60358514483.77831,
    'cex_volume_24h': 59125993293.39941,
    'dex_volume_24h': 1232521190.3789246,
    'volume_change_24h': 9.2403,
    'percent_change_1h': -0.01434979,
    'percent_change_24h': 0.02999017,
    'percent_change_7d': 0.01124163,
    'percent_change_30d': 0.05867525,
    'percent_change_60d': 0.04989957,
    'percent_change_90d': -0.06557177,
    'market_cap': 184115214372.51685,
    'market_cap_dominance': 8.1373,
    'fully_diluted_market_cap': 189005593801.15,
    'tvl': None,
    'last_updated': '2026-07-21T16:45:00.000Z'}},
  'tags': ['stablecoin',
   'asset-backed-stablecoin',
   'usd-stablecoin',
   'ethereum-pow-ecosystem',
   'fiat-stablecoin',
   'tron20-ecosystem',
   'rsk-rbtc-ecosystem',
   'venom-ecosystem',
   'world-liberty-financial-portfolio',
   'binance-ecosystem',
   'binance-listing',
   'peaq-ecosystem',
   'etherlink-ecosystem',
   'duckchain-ecosystem',
   'onus-ecosystem',
   'sophon-ecosystem',
   'xlayer-ecosystem']},
 {'id': 1839,
  'name': 'BNB',
  'symbol': 'BNB',
  'slug': 'bnb',
  'infinite_supply': False,
  'circulating_supply': 133165882.18,
  'total_supply': 133165882.18,
  'max_supply': 133165882.95,
  'date_added': '2017-07-25T00:00:00.000Z',
  'num_market_pairs': 3305,
  'cmc_rank': 4,
  'last_updated': '2026-07-21T16:46:00.000Z',
  'tvl_ratio': None,
  'platform': None,
  'self_reported_circulating_supply': None,
  'self_reported_market_cap': None,
  'minted_market_cap': 76472234307.98,
  'quote': {'USD': {'price': 574.2629647781255,
    'volume_24h': 1135220643.8551874,
    'cex_volume_24h': 1112019651.4877217,
    'dex_volume_24h': 23200992.36746547,
    'volume_change_24h': 6.9427,
    'percent_change_1h': -0.08377051,
    'percent_change_24h': 0.3096075,
    'percent_change_7d': -1.29360679,
    'percent_change_30d': -2.45898852,
    'percent_change_60d': -12.8114613,
    'percent_change_90d': -11.2142232,
    'market_cap': 76472234307.98135,
    'market_cap_dominance': 3.3798,
    'fully_diluted_market_cap': 76472234750.16,
    'tvl': None,
    'last_updated': '2026-07-21T16:46:00.000Z'}},
  'tags': ['marketplace',
   'centralized-exchange',
   'payments',
   'smart-contracts',
   'alameda-research-portfolio',
   'multicoin-capital-portfolio',
   'bnb-chain-ecosystem',
   'layer-1',
   'alleged-sec-securities',
   'celsius-bankruptcy-estate',
   'binance-ecosystem',
   'binance-listing',
   'etherlink-ecosystem',
   'made-in-china']},
 {'id': 3408,
  'name': 'USDC',
  'symbol': 'USDC',
  'slug': 'usd-coin',
  'infinite_supply': False,
  'circulating_supply': 73247323041.8707,
  'total_supply': 73247323041.8707,
  'max_supply': None,
  'date_added': '2018-10-08T00:00:00.000Z',
  'num_market_pairs': 41765,
  'cmc_rank': 5,
  'last_updated': '2026-07-21T16:46:00.000Z',
  'tvl_ratio': None,
  'platform': {'id': 1027,
   'slug': 'ethereum',
   'name': 'Ethereum',
   'symbol': 'ETH',
   'token_address': '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'},
  'self_reported_circulating_supply': 60901219650.23,
  'self_reported_market_cap': 60902146007.585815,
  'minted_market_cap': 73248437193.56,
  'quote': {'USD': {'price': 1.0000152108177986,
    'volume_24h': 10058277879.022518,
    'cex_volume_24h': 8717535517.288319,
    'dex_volume_24h': 1340742361.7341723,
    'volume_change_24h': 1.8319,
    'percent_change_1h': 0.0131577,
    'percent_change_24h': 0.00981347,
    'percent_change_7d': 0.01896273,
    'percent_change_30d': 0.01619393,
    'percent_change_60d': 0.02779333,
    'percent_change_90d': 0.03515515,
    'market_cap': 73248437193.55573,
    'market_cap_dominance': 3.2373,
    'fully_diluted_market_cap': 73248437193.56,
    'tvl': None,
    'last_updated': '2026-07-21T16:46:00.000Z'}},
  'tags': ['medium-of-exchange',
   'stablecoin',
   'asset-backed-stablecoin',
   'stellar-ecosystem',
   'coinbase-ventures-portfolio',
   'usd-stablecoin',
   'xdc-ecosystem',
   'ethereum-pow-ecosystem',
   'fiat-stablecoin',
   'tron20-ecosystem',
   'venom-ecosystem',
   'made-in-america',
   'world-liberty-financial-portfolio',
   'sonic-ecosystem',
   'binance-ecosystem',
   'binance-listing',
   'hyperevm-ecosystem',
   'etherlink-ecosystem',
   'unichain-ecosystem',
   'vector-smart-chain-ecosystem',
   'sophon-ecosystem',
   'monad-ecosystem',
   'xlayer-ecosystem']},
 {'id': 52,
  'name': 'XRP',
  'symbol': 'XRP',
  'slug': 'xrp',
  'infinite_supply': False,
  'circulating_supply': 62466503703,
  'total_supply': 99985639695,
  'max_supply': 100000000000,
  'date_added': '2013-08-04T00:00:00.000Z',
  'num_market_pairs': 1849,
  'cmc_rank': 6,
  'last_updated': '2026-07-21T16:45:00.000Z',
  'tvl_ratio': None,
  'platform': None,
  'self_reported_circulating_supply': None,
  'self_reported_market_cap': None,
  'minted_market_cap': 114959053178.76,
  'quote': {'USD': {'price': 1.1497556402042721,
    'volume_24h': 1421745768.4572835,
    'cex_volume_24h': 1420888687.6130698,
    'dex_volume_24h': 857080.84421327,
    'volume_change_24h': 28.7052,
    'percent_change_1h': 0.14109856,
    'percent_change_24h': 3.47948794,
    'percent_change_7d': 3.94313236,
    'percent_change_30d': 0.60972202,
    'percent_change_60d': -14.89034629,
    'percent_change_90d': -20.60166317,
    'market_cap': 71821214956.3653,
    'market_cap_dominance': 3.1743,
    'fully_diluted_market_cap': 114975564020.43,
    'tvl': None,
    'last_updated': '2026-07-21T16:45:00.000Z'}},
  'tags': ['medium-of-exchange',
   'enterprise-solutions',
   'xrp-ecosystem',
   'solana-ecosystem',
   'arrington-xrp-capital-portfolio',
   'galaxy-digital-portfolio',
   'a16z-portfolio',
   'pantera-capital-portfolio',
   'ftx-bankruptcy-estate',
   '2017-2018-alt-season',
   'klaytn-ecosystem',
   'made-in-america',
   'us-strategic-crypto-reserve',
   'binance-ecosystem',
   'binance-listing',
   'iso-20022',
   'sec-cftc-token-taxonomy',
   'sec-cftc-digital-commodities']},
 {'id': 5426,
  'name': 'Solana',
  'symbol': 'SOL',
  'slug': 'solana',
  'infinite_supply': True,
  'circulating_supply': 582749333.4592701,
  'total_supply': 630740640.2820572,
  'max_supply': None,
  'date_added': '2020-04-10T00:00:00.000Z',
  'num_market_pairs': 1147,
  'cmc_rank': 7,
  'last_updated': '2026-07-21T16:45:00.000Z',
  'tvl_ratio': None,
  'platform': None,
  'self_reported_circulating_supply': 525236893.3,
  'self_reported_market_cap': 41013645726.74934,
  'minted_market_cap': 49252010846.88,
  'quote': {'USD': {'price': 78.08599557633042,
    'volume_24h': 1777512419.960628,
    'cex_volume_24h': 1777491005.9092917,
    'dex_volume_24h': 21414.05133652,
    'volume_change_24h': -12.1574,
    'percent_change_1h': 0.14354252,
    'percent_change_24h': 0.69747521,
    'percent_change_7d': 0.85065189,
    'percent_change_30d': 5.58390358,
    'percent_change_60d': -9.956716,
    'percent_change_90d': -11.09975432,
    'market_cap': 45504561874.61007,
    'market_cap_dominance': 2.0112,
    'fully_diluted_market_cap': 49252010846.88,
    'tvl': None,
    'last_updated': '2026-07-21T16:45:00.000Z'}},
  'tags': ['pos',
   'platform',
   'solana-ecosystem',
   'cms-holdings-portfolio',
   'kenetic-capital-portfolio',
   'alameda-research-portfolio',
   'multicoin-capital-portfolio',
   'okx-ventures-portfolio',
   'layer-1',
   'ftx-bankruptcy-estate',
   'alleged-sec-securities',
   'cmc-crypto-awards-2024',
   'made-in-america',
   'us-strategic-crypto-reserve',
   'binance-ecosystem',
   'binance-listing',
   'sec-cftc-token-taxonomy',
   'sec-cftc-digital-commodities',
   'coinlist-launchpad']},
 {'id': 1958,
  'name': 'TRON',
  'symbol': 'TRX',
  'slug': 'tron',
  'infinite_supply': True,
  'circulating_supply': 94875121400.0912,
  'total_supply': 94875122213.2912,
  'max_supply': None,
  'date_added': '2017-09-13T00:00:00.000Z',
  'num_market_pairs': 1351,
  'cmc_rank': 8,
  'last_updated': '2026-07-21T16:46:00.000Z',
  'tvl_ratio': None,
  'platform': None,
  'self_reported_circulating_supply': 94667886298.43,
  'self_reported_market_cap': 31109751513.35065,
  'minted_market_cap': 31177853359.37,
  'quote': {'USD': {'price': 0.32861990195155105,
    'volume_24h': 407355067.9873989,
    'cex_volume_24h': 407310945.1066333,
    'dex_volume_24h': 44122.88076561,
    'volume_change_24h': -0.1392,
    'percent_change_1h': 0.07026573,
    'percent_change_24h': 0.83223955,
    'percent_change_7d': 1.16654554,
    'percent_change_30d': 0.61499966,
    'percent_change_60d': -9.35053665,
    'percent_change_90d': -0.06009984,
    'market_cap': 31177853092.139473,
    'market_cap_dominance': 1.378,
    'fully_diluted_market_cap': 31177853359.37,
    'tvl': None,
    'last_updated': '2026-07-21T16:46:00.000Z'}},
  'tags': ['media',
   'payments',
   'tron-ecosystem',
   'layer-1',
   'dwf-labs-portfolio',
   'alleged-sec-securities',
   '2017-2018-alt-season',
   'tron20-ecosystem',
   'world-liberty-financial-portfolio',
   'binance-ecosystem',
   'binance-listing',
   'made-in-china']},
 {'id': 32196,
  'name': 'Hyperliquid',
  'symbol': 'HYPE',
  'slug': 'hyperliquid',
  'infinite_supply': False,
  'circulating_supply': 252817496.96782613,
  'total_supply': 953149360.6187525,
  'max_supply': 953149975.4690608,
  'date_added': '2024-07-15T10:14:50.000Z',
  'num_market_pairs': 291,
  'cmc_rank': 9,
  'last_updated': '2026-07-21T16:46:00.000Z',
  'tvl_ratio': None,
  'platform': {'id': 32196,
   'slug': 'hyperliquid',
   'name': 'Hyperliquid',
   'symbol': 'HYPE',
   'token_address': '0x0d01dc56dcaaca66ad901c959b4011ec'},
  'self_reported_circulating_supply': 333931719,
  'self_reported_market_cap': 20631606064.87523,
  'minted_market_cap': 58889290865.1,
  'quote': {'USD': {'price': 61.783906382595625,
    'volume_24h': 302679337.27677286,
    'cex_volume_24h': 260926169.67188114,
    'dex_volume_24h': 41753167.60489164,
    'volume_change_24h': 3.2718,
    'percent_change_1h': 0.28020417,
    'percent_change_24h': -0.55955783,
    'percent_change_7d': -4.75450322,
    'percent_change_30d': -9.1121595,
    'percent_change_60d': 7.13722234,
    'percent_change_90d': 50.55423977,
    'market_cap': 15620052564.542324,
    'market_cap_dominance': 0.6904,
    'fully_diluted_market_cap': 58889328852.95,
    'tvl': None,
    'last_updated': '2026-07-21T16:46:00.000Z'}},
  'tags': ['decentralized-exchange-dex-token',
   'defi',
   'derivatives',
   'layer-1',
   'hyperliquid-ecosystem',
   'binance-ecosystem',
   'binance-listing',
   'perpetuals']},
 {'id': 74,
  'name': 'Dogecoin',
  'symbol': 'DOGE',
  'slug': 'dogecoin',
  'infinite_supply': True,
  'circulating_supply': 170876023126.57907,
  'total_supply': 170876023126.57907,
  'max_supply': None,
  'date_added': '2013-12-15T00:00:00.000Z',
  'num_market_pairs': 1454,
  'cmc_rank': 10,
  'last_updated': '2026-07-21T16:45:00.000Z',
  'tvl_ratio': None,
  'platform': None,
  'self_reported_circulating_supply': None,
  'self_reported_market_cap': None,
  'minted_market_cap': 12530213978,
  'quote': {'USD': {'price': 0.07332926965838071,
    'volume_24h': 688264883.4796077,
    'cex_volume_24h': 687950248.0135939,
    'dex_volume_24h': 314635.46601369,
    'volume_change_24h': 24.178,
    'percent_change_1h': 0.17741567,
    'percent_change_24h': 0.35899884,
    'percent_change_7d': -1.89702716,
    'percent_change_30d': -11.86699271,
    'percent_change_60d': -30.61150278,
    'percent_change_90d': -24.68329067,
    'market_cap': 12530213978.000616,
    'market_cap_dominance': 0.5538,
    'fully_diluted_market_cap': 12530213978,
    'tvl': None,
    'last_updated': '2026-07-21T16:45:00.000Z'}},
  'tags': ['mineable',
   'pow',
   'scrypt',
   'medium-of-exchange',
   'memes',
   'payments',
   'doggone-doggerel',
   'doge-chain-ecosystem',
   'osmosis-ecosystem',
   'ftx-bankruptcy-estate',
   'animal-memes',
   'made-in-america',
   'binance-ecosystem',
   'binance-listing',
   'sec-cftc-token-taxonomy',
   'sec-cftc-digital-commodities']},
 {'id': 1437,
  'name': 'Zcash',
  'symbol': 'ZEC',
  'slug': 'zcash',
  'infinite_supply': False,
  'circulating_supply': 16782403.1655448,
  'total_supply': 16782403.1655448,
  'max_supply': 21000000,
  'date_added': '2016-10-29T00:00:00.000Z',
  'num_market_pairs': 628,
  'cmc_rank': 11,
  'last_updated': '2026-07-21T16:45:00.000Z',
  'tvl_ratio': None,
  'platform': None,
  'self_reported_circulating_supply': None,
  'self_reported_market_cap': None,
  'minted_market_cap': 9035707035.79,
  'quote': {'USD': {'price': 538.4036449760889,
    'volume_24h': 472294270.104434,
    'cex_volume_24h': 445640500.08427805,
    'dex_volume_24h': 26653770.02015604,
    'volume_change_24h': -1.0595,
    'percent_change_1h': -0.29518861,
    'percent_change_24h': -2.21766339,
    'percent_change_7d': -1.07526923,
    'percent_change_30d': 20.14412505,
    'percent_change_60d': -13.75006702,
    'percent_change_90d': 66.01626841,
    'market_cap': 9035707035.787573,
    'market_cap_dominance': 0.3993,
    'fully_diluted_market_cap': 11306476544.5,
    'tvl': None,
    'last_updated': '2026-07-21T16:45:00.000Z'}},
  'tags': ['mineable',
   'pow',
   'equihash',
   'medium-of-exchange',
   'privacy',
   'zero-knowledge-proofs',
   'quantum-resistant',
   'binance-chain',
   'boostvc-portfolio',
   'dcg-portfolio',
   'electric-capital-portfolio',
   'fenbushi-capital-portfolio',
   'hashkey-capital-portfolio',
   'winklevoss-capital-portfolio',
   'placeholder-ventures-portfolio',
   'pantera-capital-portfolio',
   'layer-1',
   'standard-crypto-portfolio',
   '2017-2018-alt-season',
   'made-in-america',
   'binance-ecosystem',
   'binance-listing',
   'privacy-coins']},
 {'id': 3957,
  'name': 'UNUS SED LEO',
  'symbol': 'LEO',
  'slug': 'unus-sed-leo',
  'infinite_supply': False,
  'circulating_supply': 920152521.9,
  'total_supply': 985239504,
  'max_supply': None,
  'date_added': '2019-05-21T00:00:00.000Z',
  'num_market_pairs': 69,
  'cmc_rank': 12,
  'last_updated': '2026-07-21T16:46:00.000Z',
  'tvl_ratio': None,
  'platform': {'id': 1027,
   'slug': 'ethereum',
   'name': 'Ethereum',
   'symbol': 'ETH',
   'token_address': '0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3'},
  'self_reported_circulating_supply': None,
  'self_reported_market_cap': None,
  'minted_market_cap': 9568681425.02,
  'quote': {'USD': {'price': 9.712035891958372,
    'volume_24h': 182579.63423338,
    'cex_volume_24h': 182579.63423338,
    'dex_volume_24h': 0,
    'volume_change_24h': -42.1374,
    'percent_change_1h': -0.00179896,
    'percent_change_24h': 0.1124316,
    'percent_change_7d': 1.62104497,
    'percent_change_30d': 1.68066328,
    'percent_change_60d': -2.82512927,
    'percent_change_90d': -4.56275628,
    'market_cap': 8936554318.768812,
    'market_cap_dominance': 0.395,
    'fully_diluted_market_cap': 9568681425.02,

## Як зрозуміти структуру JSON?

In [ ]:
import json
print(json.dumps(data, indent=2))

{
  "status": {
    "timestamp": "2026-02-17T18:34:15.990Z",
    "error_code": 0,
    "error_message": null,
    "elapsed": 27,
    "credit_count": 1,
    "notice": null,
    "total_count": 8817
  },
  "data": [
    {
      "id": 1,
      "name": "Bitcoin",
      "symbol": "BTC",
      "slug": "bitcoin",
      "num_market_pairs": 12562,
      "date_added": "2010-07-13T00:00:00.000Z",
      "tags": [
        "mineable",
        "pow",
        "sha-256",
        "store-of-value",
        "state-channel",
        "coinbase-ventures-portfolio",
        "three-arrows-capital-portfolio",
        "polychain-capital-portfolio",
        "binance-labs-portfolio",
        "blockchain-capital-portfolio",
        "boostvc-portfolio",
        "cms-holdings-portfolio",
        "dcg-portfolio",
        "dragonfly-capital-portfolio",
        "electric-capital-portfolio",
        "fabric-ventures-portfolio",
        "framework-ventures-portfolio",
        "galaxy-digital-portfolio",
        "huobi-capital-portfolio",
        "alameda-research-portfolio",
        "a16z-portfolio",
        "1confirmation-portfolio",
        "winklevoss-capital-portfolio",
        "usv-portfolio",
        "placeholder-ventures-portfolio",
        "pantera-capital-portfolio",
        "multicoin-capital-portfolio",
        "paradigm-portfolio",
        "bitcoin-ecosystem",
        "layer-1",
        "ftx-bankruptcy-estate",
        "2017-2018-alt-season",
        "us-strategic-crypto-reserve",
        "binance-ecosystem",
        "binance-listing"
      ],
      "max_supply": 21000000,
      "circulating_supply": 19990837,
      "total_supply": 19990837,
      "infinite_supply": false,
      "minted_market_cap": 1354372375976.81,
      "platform": null,
      "cmc_rank": 1,
      "self_reported_circulating_supply": null,
      "self_reported_market_cap": null,
      "tvl_ratio": null,
      "last_updated": "2026-02-17T18:32:00.000Z",
      "quote": {
        "USD": {
          "price": 67749.6583047926,
          "volume_24h": 34532360650.271614,
          "volume_change_24h": -8.2989,
          "percent_change_1h": 0.5434558,
          "percent_change_24h": -0.47400661,
          "percent_change_7d": -1.82139063,
          "percent_change_30d": -28.90731081,
          "percent_change_60d": -22.27337444,
          "percent_change_90d": -23.79968753,
          "market_cap": 1354372375976.8052,
          "market_cap_dominance": 58.1023,
          "fully_diluted_market_cap": 1422742824400.64,
          "tvl": null,
          "last_updated": "2026-02-17T18:32:00.000Z"
        }
      }
    },
    {
      "id": 1027,
      "name": "Ethereum",
      "symbol": "ETH",
      "slug": "ethereum",
      "num_market_pairs": 11575,
      "date_added": "2015-08-07T00:00:00.000Z",
      "tags": [
        "pos",
        "smart-contracts",
        "ethereum-ecosystem",
        "coinbase-ventures-portfolio",
        "three-arrows-capital-portfolio",
        "polychain-capital-portfolio",
        "binance-labs-portfolio",
        "blockchain-capital-portfolio",
        "boostvc-portfolio",
        "cms-holdings-portfolio",
        "dcg-portfolio",
        "dragonfly-capital-portfolio",
        "electric-capital-portfolio",
        "fabric-ventures-portfolio",
        "framework-ventures-portfolio",
        "hashkey-capital-portfolio",
        "kenetic-capital-portfolio",
        "huobi-capital-portfolio",
        "alameda-research-portfolio",
        "a16z-portfolio",
        "1confirmation-portfolio",
        "winklevoss-capital-portfolio",
        "usv-portfolio",
        "placeholder-ventures-portfolio",
        "pantera-capital-portfolio",
        "multicoin-capital-portfolio",
        "paradigm-portfolio",
        "ethereum-pow-ecosystem",
        "layer-1",
        "ftx-bankruptcy-estate",
        "sora-ecosystem",
        "rsk-rbtc-ecosystem",
        "world-liberty-financial-portfolio",
        "us-strategic-crypto-reserve",
        "binance-ecosystem",
        "binance-listing",
        "abstract-chain-ecosystem",
        "unichain-ecosystem",
        "soneium-ecosystem",
        "sophon-ecosystem"
      ],
      "max_supply": null,
      "circulating_supply": 120692440.4714584,
      "total_supply": 120692440.4714584,
      "infinite_supply": true,
      "minted_market_cap": 240172637225.97,
      "platform": null,
      "cmc_rank": 2,
      "self_reported_circulating_supply": null,
      "self_reported_market_cap": null,
      "tvl_ratio": null,
      "last_updated": "2026-02-17T18:32:00.000Z",
      "quote": {
        "USD": {
          "price": 1989.9559267158131,
          "volume_24h": 20077621836.27437,
          "volume_change_24h": -14.2947,
          "percent_change_1h": 0.95058871,
          "percent_change_24h": 0.56114695,
          "percent_change_7d": -1.02494862,
          "percent_change_30d": -40.69917711,
          "percent_change_60d": -32.85072037,
          "percent_change_90d": -31.05549279,
          "market_cap": 240172637225.97412,
          "market_cap_dominance": 10.3034,
          "fully_diluted_market_cap": 240172637225.97,
          "tvl": null,
          "last_updated": "2026-02-17T18:32:00.000Z"
        }
      }
    },
    {
      "id": 825,
      "name": "Tether USDt",
      "symbol": "USDT",
      "slug": "tether",
      "num_market_pairs": 171317,
      "date_added": "2015-02-25T00:00:00.000Z",
      "tags": [
        "stablecoin",
        "asset-backed-stablecoin",
        "usd-stablecoin",
        "ethereum-pow-ecosystem",
        "fiat-stablecoin",
        "tron20-ecosystem",
        "rsk-rbtc-ecosystem",
        "venom-ecosystem",
        "world-liberty-financial-portfolio",
        "binance-ecosystem",
        "binance-listing",
        "peaq-ecosystem",
        "apertum-ecosystem",
        "etherlink-ecosystem",
        "duckchain-ecosystem",
        "onus-ecosystem",
        "sophon-ecosystem",
        "zedxion-smart-chain-ecosystem",
        "xlayer-ecosystem"
      ],
      "max_supply": null,
      "circulating_supply": 183751887997.06967,
      "total_supply": 187956018072.05417,
      "platform": {
        "id": 1027,
        "name": "Ethereum",
        "symbol": "ETH",
        "slug": "ethereum",
        "token_address": "0xdac17f958d2ee523a2206206994597c13d831ec7"
      },
      "infinite_supply": true,
      "minted_market_cap": 187900094328.29,
      "cmc_rank": 3,
      "self_reported_circulating_supply": null,
      "self_reported_market_cap": null,
      "tvl_ratio": null,
      "last_updated": "2026-02-17T18:32:00.000Z",
      "quote": {
        "USD": {
          "price": 0.9997024636702643,
          "volume_24h": 73203077365.39919,
          "volume_change_24h": -10.9287,
          "percent_change_1h": 0.02213025,
          "percent_change_24h": 0.03074977,
          "percent_change_7d": 0.0244349,
          "percent_change_30d": 0.0005158,
          "percent_change_60d": 0.01572791,
          "percent_change_90d": 0.05205536,
          "market_cap": 183697215134.733,
          "market_cap_dominance": 7.8806,
          "fully_diluted_market_cap": 187900094328.29,
          "tvl": null,
          "last_updated": "2026-02-17T18:32:00.000Z"
        }
      }
    },
    {
      "id": 52,
      "name": "XRP",
      "symbol": "XRP",
      "slug": "xrp",
      "num_market_pairs": 1799,
      "date_added": "2013-08-04T00:00:00.000Z",
      "tags": [
        "medium-of-exchange",
        "enterprise-solutions",
        "xrp-ecosystem",
        "arrington-xrp-capital-portfolio",
        "galaxy-digital-portfolio",
        "a16z-portfolio",
        "pantera-capital-portfolio",
        "ftx-bankruptcy-estate",
        "2017-2018-alt-season",
        "klaytn-ecosystem",
        "made-in-america",
        "us-strategic-crypto-reserve",
        "binance-ecosystem",
        "binance-listing",
        "iso-20022"
      ],
      "max_supply": 100000000000,
      "circulating_supply": 60917315351,
      "total_supply": 99985721048,
      "infinite_supply": false,
      "minted_market_cap": 148321070049.14,
      "platform": null,
      "cmc_rank": 4,
      "self_reported_circulating_supply": null,
      "self_reported_market_cap": null,
      "tvl_ratio": null,
      "last_updated": "2026-02-17T18:32:00.000Z",
      "quote": {
        "USD": {
          "price": 1.483422517680669,
          "volume_24h": 2349362417.8261366,
          "volume_change_24h": -36.982,
          "percent_change_1h": 0.71207348,
          "percent_change_24h": 0.21668806,
          "percent_change_7d": 5.62616236,
          "percent_change_30d": -27.95868224,
          "percent_change_60d": -21.46166821,
          "percent_change_90d": -27.31810291,
          "market_cap": 90366117308.32768,
          "market_cap_dominance": 3.8767,
          "fully_diluted_market_cap": 148342251768.07,
          "tvl": null,
          "last_updated": "2026-02-17T18:32:00.000Z"
        }
      }
    },
    {
      "id": 1839,
      "name": "BNB",
      "symbol": "BNB",
      "slug": "bnb",
      "num_market_pairs": 3135,
      "date_added": "2017-07-25T00:00:00.000Z",
      "tags": [
        "marketplace",
        "centralized-exchange",
        "payments",
        "smart-contracts",
        "alameda-research-portfolio",
        "multicoin-capital-portfolio",
        "bnb-chain-ecosystem",
        "layer-1",
        "alleged-sec-securities",
        "celsius-bankruptcy-estate",
        "binance-ecosystem",
        "binance-listing",
        "etherlink-ecosystem",
        "made-in-china"
      ],
      "max_supply": 136359194.34,
      "circulating_supply": 136359194.34,
      "total_supply": 136359194.34,
      "infinite_supply": false,
      "minted_market_cap": 84529709138.14,
      "platform": null,
      "cmc_rank": 5,
      "self_reported_circulating_supply": null,
      "self_reported_market_cap": null,
      "tvl_ratio": null,
      "last_updated": "2026-02-17T18:32:00.000Z",
      "quote": {
        "USD": {
          "price": 619.9047269769981,
          "volume_24h": 1311959320.5820568,
          "volume_change_24h": -9.0836,
          "percent_change_1h": 0.45371721,
          "percent_change_24h": 0.53712613,
          "percent_change_7d": 0.43749222,
          "percent_change_30d": -34.86553222,
          "percent_change_60d": -26.86349874,
          "percent_change_90d": -29.06740685,
          "market_cap": 84529709138.14113,
          "market_cap_dominance": 3.6263,
          "fully_diluted_market_cap": 84529709138.14,
          "tvl": null,
          "last_updated": "2026-02-17T18:32:00.000Z"
        }
      }
    },
    {
      "id": 3408,
      "name": "USDC",
      "symbol": "USDC",
      "slug": "usd-coin",
      "num_market_pairs": 37516,
      "date_added": "2018-10-08T00:00:00.000Z",
      "tags": [
        "medium-of-exchange",
        "stablecoin",
        "asset-backed-stablecoin",
        "stellar-ecosystem",
        "coinbase-ventures-portfolio",
        "usd-stablecoin",
        "xdc-ecosystem",
        "ethereum-pow-ecosystem",
        "fiat-stablecoin",
        "tron20-ecosystem",
        "venom-ecosystem",
        "made-in-america",
        "world-liberty-financial-portfolio",
        "sonic-ecosystem",
        "binance-ecosystem",
        "binance-listing",
        "hyperevm-ecosystem",
        "etherlink-ecosystem",
        "unichain-ecosystem",
        "vector-smart-chain-ecosystem",
        "sophon-ecosystem",
        "monad-ecosystem",
        "xlayer-ecosystem"
      ],
      "max_supply": null,
      "circulating_supply": 73579685072.68916,
      "total_supply": 73579685072.68916,
      "platform": {
        "id": 1027,
        "name": "Ethereum",
        "symbol": "ETH",
        "slug": "ethereum",
        "token_address": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
      },
      "infinite_supply": false,
      "minted_market_cap": 73613926417.61,
      "cmc_rank": 6,
      "self_reported_circulating_supply": 60901219650.23,
      "self_reported_market_cap": 60929560892.327774,
      "tvl_ratio": null,
      "last_updated": "2026-02-17T18:32:00.000Z",
      "quote": {
        "USD": {
          "price": 1.0004653641135686,
          "volume_24h": 10018453191.817396,
          "volume_change_24h": 0.2202,
          "percent_change_1h": 0.05866934,
          "percent_change_24h": 0.05757253,
          "percent_change_7d": 0.05434321,
          "percent_change_30d": 0.06172181,
          "percent_change_60d": 0.0649039,
          "percent_change_90d": 0.04923062,
          "market_cap": 73613926417.60966,
          "market_cap_dominance": 3.158,
          "fully_diluted_market_cap": 73613926417.61,
          "tvl": null,
          "last_updated": "2026-02-17T18:32:00.000Z"
        }
      }
    },
    {
      "id": 5426,
      "name": "Solana",
      "symbol": "SOL",
      "slug": "solana",
      "num_market_pairs": 1089,
      "date_added": "2020-04-10T00:00:00.000Z",
      "tags": [
        "pos",
        "platform",
        "solana-ecosystem",
        "cms-holdings-portfolio",
        "kenetic-capital-portfolio",
        "alameda-research-portfolio",
        "multicoin-capital-portfolio",
        "okx-ventures-portfolio",
        "layer-1",
        "ftx-bankruptcy-estate",
        "alleged-sec-securities",
        "cmc-crypto-awards-2024",
        "made-in-america",
        "us-strategic-crypto-reserve",
        "binance-ecosystem",
        "binance-listing"
      ],
      "max_supply": null,
      "circulating_supply": 568200529.0883174,
      "total_supply": 620661365.7311043,
      "infinite_supply": true,
      "minted_market_cap": 52691924118.57,
      "platform": null,
      "cmc_rank": 7,
      "self_reported_circulating_supply": 525236893.3,
      "self_reported_market_cap": 44590728622.90068,
      "tvl_ratio": null,
      "last_updated": "2026-02-17T18:32:00.000Z",
      "quote": {
        "USD": {
          "price": 84.89641377387356,
          "volume_24h": 3114105624.406045,
          "volume_change_24h": -18.4731,
          "percent_change_1h": 1.10847998,
          "percent_change_24h": 0.14241502,
          "percent_change_7d": 1.67404036,
          "percent_change_30d": -40.443853,
          "percent_change_60d": -31.78029804,
          "percent_change_90d": -35.101143,
          "market_cap": 48238187224.01567,
          "market_cap_dominance": 2.0694,
          "fully_diluted_market_cap": 52691924118.57,
          "tvl": null,
          "last_updated": "2026-02-17T18:32:00.000Z"
        }
      }
    },
    {
      "id": 1958,
      "name": "TRON",
      "symbol": "TRX",
      "slug": "tron",
      "num_market_pairs": 1300,
      "date_added": "2017-09-13T00:00:00.000Z",
      "tags": [
        "media",
        "payments",
        "tron-ecosystem",
        "layer-1",
        "dwf-labs-portfolio",
        "alleged-sec-securities",
        "2017-2018-alt-season",
        "tron20-ecosystem",
        "world-liberty-financial-portfolio",
        "binance-ecosystem",
        "binance-listing",
        "made-in-china"
      ],
      "max_supply": null,
      "circulating_supply": 94726859539.7531,
      "total_supply": 94726862820.763,
      "infinite_supply": true,
      "minted_market_cap": 26673163730.05,
      "platform": null,
      "cmc_rank": 8,
      "self_reported_circulating_supply": 94667886298.43,
      "self_reported_market_cap": 26656557137.26624,
      "tvl_ratio": null,
      "last_updated": "2026-02-17T18:33:00.000Z",
      "quote": {
        "USD": {
          "price": 0.28157972232774275,
          "volume_24h": 619640255.3030976,
          "volume_change_24h": 11.9351,
          "percent_change_1h": 0.25327041,
          "percent_change_24h": -0.50861006,
          "percent_change_7d": 1.52379392,
          "percent_change_30d": -11.97033535,
          "percent_change_60d": 1.02181816,
          "percent_change_90d": -0.68657995,
          "market_cap": 26673162806.182766,
          "market_cap_dominance": 1.1432,
          "fully_diluted_market_cap": 26673163730.05,
          "tvl": null,
          "last_updated": "2026-02-17T18:33:00.000Z"
        }
      }
    },
    {
      "id": 74,
      "name": "Dogecoin",
      "symbol": "DOGE",
      "slug": "dogecoin",
      "num_market_pairs": 1401,
      "date_added": "2013-12-15T00:00:00.000Z",
      "tags": [
        "mineable",
        "pow",
        "scrypt",
        "medium-of-exchange",
        "memes",
        "payments",
        "doggone-doggerel",
        "doge-chain-ecosystem",
        "osmosis-ecosystem",
        "ftx-bankruptcy-estate",
        "animal-memes",
        "made-in-america",
        "binance-ecosystem",
        "binance-listing"
      ],
      "max_supply": null,
      "circulating_supply": 168780453126.57907,
      "total_supply": 168780453126.57907,
      "infinite_supply": true,
      "minted_market_cap": 17161264481.46,
      "platform": null,
      "cmc_rank": 9,
      "self_reported_circulating_supply": null,
      "self_reported_market_cap": null,
      "tvl_ratio": null,
      "last_updated": "2026-02-17T18:32:00.000Z",
      "quote": {
        "USD": {
          "price": 0.1016780329923267,
          "volume_24h": 1023484379.7345098,
          "volume_change_24h": -26.1489,
          "percent_change_1h": 0.58211531,
          "percent_change_24h": 0.96239516,
          "percent_change_7d": 9.51266778,
          "percent_change_30d": -25.99344575,
          "percent_change_60d": -22.40478052,
          "percent_change_90d": -31.10697744,
          "market_cap": 17161264481.464155,
          "market_cap_dominance": 0.7362,
          "fully_diluted_market_cap": 17161264481.46,
          "tvl": null,
          "last_updated": "2026-02-17T18:32:00.000Z"
        }
      }
    },
    {
      "id": 1831,
      "name": "Bitcoin Cash",
      "symbol": "BCH",
      "slug": "bitcoin-cash",
      "num_market_pairs": 1137,
      "date_added": "2017-07-23T00:00:00.000Z",
      "tags": [
        "mineable",
        "pow",
        "sha-256",
        "marketplace",
        "medium-of-exchange",
        "store-of-value",
        "enterprise-solutions",
        "payments",
        "layer-1",
        "2017-2018-alt-season",
        "made-in-america",
        "binance-ecosystem",
        "binance-listing"
      ],
      "max_supply": 21000000,
      "circulating_supply": 19996171.875,
      "total_supply": 19996171.875,
      "infinite_supply": false,
      "minted_market_cap": 11283989781.54,
      "platform": null,
      "cmc_rank": 10,
      "self_reported_circulating_supply": null,
      "self_reported_market_cap": null,
      "tvl_ratio": null,
      "last_updated": "2026-02-17T18:32:00.000Z",
      "quote": {
        "USD": {
          "price": 564.3075010594799,
          "volume_24h": 393683394.5503245,
          "volume_change_24h": 16.2774,
          "percent_change_1h": -0.18281141,
          "percent_change_24h": 0.0641242,
          "percent_change_7d": 9.02151566,
          "percent_change_30d": -4.91617141,
          "percent_change_60d": -7.62934477,
          "percent_change_90d": 19.40581746,
          "market_cap": 11283989781.537106,
          "market_cap_dominance": 0.4841,
          "fully_diluted_market_cap": 11850457522.25,
          "tvl": null,
          "last_updated": "2026-02-17T18:32:00.000Z"
        }
      }
    }
  ]
}

## Витягуємо корисні дані у DataFrame

In [28]:
coins = data['data']  # список словників
print(type(coins), len(coins))

<class 'list'> 30

In [ ]:
coins[0]

{'id': 1,
 'name': 'Bitcoin',
 'symbol': 'BTC',
 'slug': 'bitcoin',
 'num_market_pairs': 12518,
 'date_added': '2010-07-13T00:00:00.000Z',
 'tags': ['mineable',
  'pow',
  'sha-256',
  'store-of-value',
  'state-channel',
  'coinbase-ventures-portfolio',
  'three-arrows-capital-portfolio',
  'polychain-capital-portfolio',
  'binance-labs-portfolio',
  'blockchain-capital-portfolio',
  'boostvc-portfolio',
  'cms-holdings-portfolio',
  'dcg-portfolio',
  'dragonfly-capital-portfolio',
  'electric-capital-portfolio',
  'fabric-ventures-portfolio',
  'framework-ventures-portfolio',
  'galaxy-digital-portfolio',
  'huobi-capital-portfolio',
  'alameda-research-portfolio',
  'a16z-portfolio',
  '1confirmation-portfolio',
  'winklevoss-capital-portfolio',
  'usv-portfolio',
  'placeholder-ventures-portfolio',
  'pantera-capital-portfolio',
  'multicoin-capital-portfolio',
  'paradigm-portfolio',
  'bitcoin-ecosystem',
  'layer-1',
  'ftx-bankruptcy-estate',
  '2017-2018-alt-season',
  'us-strategic-crypto-reserve',
  'binance-ecosystem',
  'binance-listing'],
 'max_supply': 21000000,
 'circulating_supply': 19976631,
 'total_supply': 19976631,
 'infinite_supply': False,
 'minted_market_cap': 1892653838586.89,
 'platform': None,
 'cmc_rank': 1,
 'self_reported_circulating_supply': None,
 'self_reported_market_cap': None,
 'tvl_ratio': None,
 'last_updated': '2026-01-16T17:22:00.000Z',
 'quote': {'USD': {'price': 94743.39484905578,
   'volume_24h': 41026964714.04858,
   'volume_change_24h': -25.737,
   'percent_change_1h': -0.10787037,
   'percent_change_24h': -1.85799627,
   'percent_change_7d': 3.98780545,
   'percent_change_30d': 8.89460501,
   'percent_change_60d': 0.98729265,
   'percent_change_90d': -11.28655649,
   'market_cap': 1892653838586.888,
   'market_cap_dominance': 59.0676,
   'fully_diluted_market_cap': 1989611291830.17,
   'tvl': None,
   'last_updated': '2026-01-16T17:22:00.000Z'}}}

In [29]:
df = pd.DataFrame(coins)

df

,id,name,symbol,slug,infinite_supply,circulating_supply,total_supply,max_supply,date_added,num_market_pairs,cmc_rank,last_updated,tvl_ratio,platform,self_reported_circulating_supply,self_reported_market_cap,minted_market_cap,quote,tags
0,1,Bitcoin,BTC,bitcoin,False,2.005944e+07,2.005944e+07,2.100000e+07,2010-07-13T00:00:00.000Z,12670,1,2026-07-21T16:46:00.000Z,None,None,NaN,NaN,1.333694e+12,"{'USD': {'price': 66487.12394842395, 'volume_2...","[mineable, pow, sha-256, store-of-value, state..."
1,1027,Ethereum,ETH,ethereum,True,1.206828e+08,1.206828e+08,NaN,2015-08-07T00:00:00.000Z,12210,2,2026-07-21T16:46:00.000Z,None,None,NaN,NaN,2.320239e+11,"{'USD': {'price': 1922.5932437718477, 'volume_...","[pos, smart-contracts, ethereum-ecosystem, coi..."
2,825,Tether USDt,USDT,tether,True,1.842194e+11,1.891126e+11,NaN,2015-02-25T00:00:00.000Z,190777,3,2026-07-21T16:45:00.000Z,None,"{'id': 1027, 'slug': 'ethereum', 'name': 'Ethe...",NaN,NaN,1.890056e+11,"{'USD': {'price': 0.9994342122682723, 'volume_...","[stablecoin, asset-backed-stablecoin, usd-stab..."
3,1839,BNB,BNB,bnb,False,1.331659e+08,1.331659e+08,1.331659e+08,2017-07-25T00:00:00.000Z,3305,4,2026-07-21T16:46:00.000Z,None,None,NaN,NaN,7.647223e+10,"{'USD': {'price': 574.2629647781255, 'volume_2...","[marketplace, centralized-exchange, payments, ..."
4,3408,USDC,USDC,usd-coin,False,7.324732e+10,7.324732e+10,NaN,2018-10-08T00:00:00.000Z,41765,5,2026-07-21T16:46:00.000Z,None,"{'id': 1027, 'slug': 'ethereum', 'name': 'Ethe...",6.090122e+10,6.090215e+10,7.324844e+10,"{'USD': {'price': 1.0000152108177986, 'volume_...","[medium-of-exchange, stablecoin, asset-backed-..."
5,52,XRP,XRP,xrp,False,6.246650e+10,9.998564e+10,1.000000e+11,2013-08-04T00:00:00.000Z,1849,6,2026-07-21T16:45:00.000Z,None,None,NaN,NaN,1.149591e+11,"{'USD': {'price': 1.1497556402042721, 'volume_...","[medium-of-exchange, enterprise-solutions, xrp..."
6,5426,Solana,SOL,solana,True,5.827493e+08,6.307406e+08,NaN,2020-04-10T00:00:00.000Z,1147,7,2026-07-21T16:45:00.000Z,None,None,5.252369e+08,4.101365e+10,4.925201e+10,"{'USD': {'price': 78.08599557633042, 'volume_2...","[pos, platform, solana-ecosystem, cms-holdings..."
7,1958,TRON,TRX,tron,True,9.487512e+10,9.487512e+10,NaN,2017-09-13T00:00:00.000Z,1351,8,2026-07-21T16:46:00.000Z,None,None,9.466789e+10,3.110975e+10,3.117785e+10,"{'USD': {'price': 0.32861990195155105, 'volume...","[media, payments, tron-ecosystem, layer-1, dwf..."
8,32196,Hyperliquid,HYPE,hyperliquid,False,2.528175e+08,9.531494e+08,9.531500e+08,2024-07-15T10:14:50.000Z,291,9,2026-07-21T16:46:00.000Z,None,"{'id': 32196, 'slug': 'hyperliquid', 'name': '...",3.339317e+08,2.063161e+10,5.888929e+10,"{'USD': {'price': 61.783906382595625, 'volume_...","[decentralized-exchange-dex-token, defi, deriv..."
9,74,Dogecoin,DOGE,dogecoin,True,1.708760e+11,1.708760e+11,NaN,2013-12-15T00:00:00.000Z,1454,10,2026-07-21T16:45:00.000Z,None,None,NaN,NaN,1.253021e+10,"{'USD': {'price': 0.07332926965838071, 'volume...","[mineable, pow, scrypt, medium-of-exchange, me..."
10,1437,Zcash,ZEC,zcash,False,1.678240e+07,1.678240e+07,2.100000e+07,2016-10-29T00:00:00.000Z,628,11,2026-07-21T16:45:00.000Z,None,None,NaN,NaN,9.035707e+09,"{'USD': {'price': 538.4036449760889, 'volume_2...","[mineable, pow, equihash, medium-of-exchange, ..."
11,3957,UNUS SED LEO,LEO,unus-sed-leo,False,9.201525e+08,9.852395e+08,NaN,2019-05-21T00:00:00.000Z,69,12,2026-07-21T16:46:00.000Z,None,"{'id': 1027, 'slug': 'ethereum', 'name': 'Ethe...",NaN,NaN,9.568681e+09,"{'USD': {'price': 9.712035891958372, 'volume_2...","[marketplace, centralized-exchange, discount-t..."
12,512,Stellar,XLM,stellar,False,3.416918e+10,5.000179e+10,5.000181e+10,2014-08-05T00:00:00.000Z,827,13,2026-07-21T16:46:00.000Z,None,None,3.153141e+10,6.098396e+09,9.670696e+09,"{'USD': {'price': 0.19340701605841532, 'volume...","[medium-of-exchange, enterprise-solutions, dec..."
13,328,Monero,XMR,monero,True,1.878089e+07,1.878089e+07,NaN,2014-05-21T00:00:00.000Z,372,14,2026-07-21T16:46:00.000Z,None,None,NaN,NaN,6.533517e+09,"{'USD': {'price': 347.8811804508256, 'volume_2...","[mineable, pow, medium-of-exchange, privacy, r..."
14,1975,Chainlink,LINK,chainlink,False,7.481000e+08,1.000000e+09,1.000000e+09,2017-09-20T00:00:00.000Z,2257,15,2026-07-21T16:46:00.000Z,None,"{'id': 1027, 'slug': 'ethereum', 'name': 'Ethe...",NaN,NaN,8.670828e+09,"{'USD': {'price': 8.67082823623115, 'volume_24...","[platform, cosmos-ecosystem, defi, privacy, in..."
15,2010,Cardano,ADA,cardano,False,3.648645e+10,4.499263e+10,4.500000e+10,2017-10-01T00:00:00.000Z,1718,16,2026-07-21T16:46:00.000Z,None,None,3.799790e+10,6.584277e+09,7.796324e+09,"{'USD': {'price': 0.17328000693013537, 'volume...","[dpos, pos, platform, research, smart-contract..."
16,37263,Canton,CC,canton-network,True,3.912761e+10,3.912761e+10,NaN,2025-07-08T04:07:45.000Z,108,17,2026-07-21T16:45:00.000Z,None,None,3.912713e+10,4.906735e+09,4.906795e+09,"{'USD': {'price': 0.12540491314252963, 'volume...","[proof-of-authority, store-of-value, enterpris..."
17,4943,Dai,DAI,multi-collateral-dai,True,4.637134e+09,4.637134e+09,NaN,2019-11-22T00:00:00.000Z,3771,18,2026-07-21T16:46:00.000Z,None,"{'id': 1027, 'slug': 'ethereum', 'name': 'Ethe...",NaN,NaN,4.636026e+09,"{'USD': {'price': 0.9997611099122322, 'volume_...","[defi, stablecoin, asset-backed-stablecoin, us..."
18,1831,Bitcoin Cash,BCH,bitcoin-cash,False,2.006438e+07,2.006438e+07,2.100000e+07,2017-07-23T00:00:00.000Z,1172,19,2026-07-21T16:45:00.000Z,None,None,NaN,NaN,4.518753e+09,"{'USD': {'price': 225.21273760912757, 'volume_...","[mineable, pow, sha-256, marketplace, medium-o..."
19,36148,World Liberty Financial USD,USD1,usd1,False,4.179450e+09,4.179450e+09,NaN,2025-04-13T05:37:56.000Z,1225,20,2026-07-21T16:46:00.000Z,None,"{'id': 1027, 'slug': 'ethereum', 'name': 'Ethe...",NaN,NaN,4.176222e+09,"{'USD': {'price': 0.9992276422705274, 'volume_...","[stablecoin, asset-backed-stablecoin, usd-stab..."
20,11419,Gram (prev. Toncoin),GRAM,gram,True,2.731028e+09,5.218214e+09,NaN,2021-08-26T13:40:22.000Z,906,21,2026-07-21T16:46:00.000Z,None,None,2.710000e+09,4.135719e+09,7.963495e+09,"{'USD': {'price': 1.5260957215190598, 'volume_...","[pos, layer-1, ftx-bankruptcy-estate, dwf-labs..."
21,29470,Ethena USDe,USDe,ethena-usde,True,4.036054e+09,4.036054e+09,NaN,2024-02-20T11:05:01.000Z,320,22,2026-07-21T16:45:00.000Z,None,"{'id': 1027, 'slug': 'ethereum', 'name': 'Ethe...",NaN,NaN,4.036256e+09,"{'USD': {'price': 1.0000498568406573, 'volume_...","[stablecoin, asset-backed-stablecoin, binance-..."
22,2,Litecoin,LTC,litecoin,False,7.741266e+07,8.400000e+07,8.400000e+07,2013-04-28T00:00:00.000Z,1542,23,2026-07-21T16:46:00.000Z,None,None,NaN,NaN,3.997430e+09,"{'USD': {'price': 47.58845565203932, 'volume_2...","[mineable, pow, scrypt, medium-of-exchange, pr..."
23,33793,Global Dollar,USDG,global-dollar-usdg,False,3.241471e+09,3.241471e+09,NaN,2024-11-05T04:54:47.000Z,161,24,2026-07-21T16:46:00.000Z,None,"{'id': 1027, 'slug': 'ethereum', 'name': 'Ethe...",1.075014e+07,1.075029e+07,3.241515e+09,"{'USD': {'price': 1.0000136089382368, 'volume_...","[stablecoin, asset-backed-stablecoin, usd-stab..."
24,20947,Sui,SUI,sui,False,4.052334e+09,1.000000e+10,1.000000e+10,2022-07-12T08:03:11.000Z,950,25,2026-07-21T16:46:00.000Z,None,None,4.052334e+09,3.111667e+09,7.678704e+09,"{'USD': {'price': 0.767870424843127, 'volume_2...","[binance-launchpool, coinbase-ventures-portfol..."
25,4642,Hedera,HBAR,hedera,False,4.379110e+10,5.000000e+10,5.000000e+10,2019-09-17T00:00:00.000Z,440,26,2026-07-21T16:45:00.000Z,None,None,NaN,NaN,3.426111e+09,"{'USD': {'price': 0.06852221922748399, 'volume...","[dag, marketplace, enterprise-solutions, payme..."
26,5805,Avalanche,AVAX,avalanche,False,4.317720e+08,4.634411e+08,7.157487e+08,2020-07-13T00:00:00.000Z,1100,27,2026-07-21T16:45:00.000Z,None,None,NaN,NaN,3.071201e+09,"{'USD': {'price': 6.626950586635258, 'volume_2...","[smart-contracts, three-arrows-capital-portfol..."
27,3635,Cronos,CRO,cronos,False,4.726824e+10,9.880158e+10,1.000000e+11,2018-12-14T00:00:00.000Z,350,28,2026-07-21T16:45:00.000Z,None,None,9.739321e+10,5.718531e+09,5.801225e+09,"{'USD': {'price': 0.0587159104873517, 'volume_...","[medium-of-exchange, centralized-exchange, mob..."
28,27772,PayPal USD,PYUSD,paypal-usd,False,2.763855e+09,2.763855e+09,NaN,2023-08-21T14:30:00.000Z,168,29,2026-07-21T16:45:00.000Z,None,"{'id': 1027, 'slug': 'ethereum', 'name': 'Ethe...",NaN,NaN,2.763484e+09,"{'USD': {'price': 0.9998657028142757, 'volume_...","[stablecoin, asset-backed-stablecoin, stellar-..."
29,6535,NEAR Protocol,NEAR,near-protocol,False,1.301446e+09,1.301446e+09,NaN,2020-08-11T00:00:00.000Z,649,30,2026-07-21T16:46:00.000Z,None,None,1.209203e+09,2.345305e+09,2.524215e+09,"{'USD': {'price': 1.9395470032082773, 'volume_...","[platform, ai-big-data, staking, coinbase-vent..."

In [31]:
url = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest"

headers = {
    "Accepts": "application/json",
    "X-CMC_PRO_API_KEY": "17ad748a-f734-46e1-8ae0-16044d2215b8"
}
params = {
    "start": "1",
    "limit": "100",
    "convert": "USD"
}

response = requests.get(url, headers=headers, params=params)

df = pd.json_normalize(response.json(), record_path='data')

In [32]:
df

,id,name,symbol,slug,infinite_supply,circulating_supply,total_supply,max_supply,date_added,num_market_pairs,...,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.slug,platform.name,platform.symbol,platform.token_address
0,1,Bitcoin,BTC,bitcoin,False,2.005944e+07,2.005944e+07,2.100000e+07,2010-07-13T00:00:00.000Z,12670,...,1.334070e+12,59.0049,1.396623e+12,NaN,2026-07-21T16:52:00.000Z,NaN,NaN,NaN,NaN,NaN
1,1027,Ethereum,ETH,ethereum,True,1.206828e+08,1.206828e+08,NaN,2015-08-07T00:00:00.000Z,12210,...,2.323388e+11,10.2762,2.323388e+11,NaN,2026-07-21T16:52:00.000Z,NaN,NaN,NaN,NaN,NaN
2,825,Tether USDt,USDT,tether,True,1.842194e+11,1.891126e+11,NaN,2015-02-25T00:00:00.000Z,190777,...,1.841003e+11,8.1426,1.889903e+11,NaN,2026-07-21T16:51:00.000Z,1027.0,ethereum,Ethereum,ETH,0xdac17f958d2ee523a2206206994597c13d831ec7
3,1839,BNB,BNB,bnb,False,1.331659e+08,1.331659e+08,1.331659e+08,2017-07-25T00:00:00.000Z,3305,...,7.646378e+10,3.3819,7.646378e+10,NaN,2026-07-21T16:52:00.000Z,NaN,NaN,NaN,NaN,NaN
4,3408,USDC,USDC,usd-coin,False,7.324732e+10,7.324732e+10,NaN,2018-10-08T00:00:00.000Z,41765,...,7.323673e+10,3.2392,7.323673e+10,NaN,2026-07-21T16:51:00.000Z,1027.0,ethereum,Ethereum,ETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,22861,Celestia,TIA,celestia,False,9.199330e+08,1.168685e+09,NaN,2023-10-31T16:51:41.000Z,360,...,3.344279e+08,0.0148,4.248581e+08,NaN,2026-07-21T16:51:00.000Z,12220.0,osmosis,Osmosis,OSMO,ibc/D79E7D83AB399BFFF93433E54FAA480C191248FC55...
96,28081,SPX6900,SPX,spx6900,False,9.309931e+08,9.309931e+08,1.000000e+09,2023-08-17T10:00:00.000Z,522,...,3.316766e+08,0.0147,3.562611e+08,NaN,2026-07-21T16:52:00.000Z,1027.0,ethereum,Ethereum,ETH,0xe0f63a424a4439cbe457d80e4f4b51ad25b2c56c
97,8000,Lido DAO,LDO,lido-dao,False,8.363623e+08,1.000000e+09,NaN,2020-12-15T00:00:00.000Z,636,...,3.268365e+08,0.0145,3.907833e+08,1.769596e+10,2026-07-21T16:52:00.000Z,1027.0,ethereum,Ethereum,ETH,0x5a98fcbea516cf06857215779fd812ca3bef1b32
98,6538,Curve DAO Token,CRV,curve-dao-token,False,1.531089e+09,2.401830e+09,3.030303e+09,2020-08-14T00:00:00.000Z,969,...,3.270562e+08,0.0145,6.473034e+08,NaN,2026-07-21T16:51:00.000Z,1027.0,ethereum,Ethereum,ETH,0xD533a949740bb3306d119CC777fa900bA034cd52
99,4172,Terra Classic,LUNC,terra-luna,False,5.527045e+12,6.454077e+12,6.454078e+12,2019-07-26T00:00:00.000Z,551,...,3.229266e+08,0.0143,3.770900e+08,NaN,2026-07-21T16:52:00.000Z,NaN,NaN,NaN,NaN,NaN

## Як розуміти документацію:

* `GET` — означає, що потрібно робити GET-запит
* У дужках `required` / `optional` — обов’язковий або необов’язковий параметр
* Тип даних: `string`, `int`, `float`

## Як відлагоджувати:

* `response.status_code != 200` — означає помилку (https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status)
* `response.text` — покаже текст помилки
* `try-except` — ловити помилки

## Отримати топ-10 криптовалют за ринковою капіталізацією

## Відфільтрувати монети з падінням більше ніж на 1%

## Побудувати barplot