<a href="https://colab.research.google.com/github/cpython-projects/python_da_17_03_26/blob/main/lesson_11_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Task 1.** Завантажте датасет Titanic ([https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv](https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv))

In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [2]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

**Task 2.** Залиште тільки необхідні стовпці:
`'PassengerId', 'Name', 'Age', 'Sex', 'Survived', 'SibSp', 'Parch', 'Fare', 'Pclass', 'Embarked'`

In [3]:
df_filtered = df[['PassengerId', 'Name', 'Age', 'Sex', 'Survived', 'SibSp', 'Parch', 'Fare', 'Pclass', 'Embarked']]
df_filtered

,PassengerId,Name,Age,Sex,Survived,SibSp,Parch,Fare,Pclass,Embarked
0,1,"Braund, Mr. Owen Harris",22.0,male,0,1,0,7.2500,3,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,female,1,1,0,71.2833,1,C
2,3,"Heikkinen, Miss. Laina",26.0,female,1,0,0,7.9250,3,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,female,1,1,0,53.1000,1,S
4,5,"Allen, Mr. William Henry",35.0,male,0,0,0,8.0500,3,S
...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",27.0,male,0,0,0,13.0000,2,S
887,888,"Graham, Miss. Margaret Edith",19.0,female,1,0,0,30.0000,1,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,female,0,1,2,23.4500,3,S
889,890,"Behr, Mr. Karl Howell",26.0,male,1,0,0,30.0000,1,C
890,891,"Dooley, Mr. Patrick",32.0,male,0,0,0,7.7500,3,Q

**Task 3.**
* Виведіть кількість рядків і стовпців
* Скільки унікальних значень у стовпці `Embarked`?
* Який максимальний і мінімальний вік пасажирів?

In [6]:
rows, columns = df_filtered.shape
print(f'Number of Rows {rows}; Number of columns {columns}')

Number of Rows 891; Number of columns 10

In [7]:
len(df_filtered.Embarked.unique())

4

In [9]:
df_filtered.Age.min()

0.42

In [10]:
df_filtered.Age.max()

80.0

In [12]:
df_filtered.Age.min(), df_filtered.Age.max()

(0.42, 80.0)

**Task 4.**
* Додайте стовпець `IsAlone`, у якому буде `True`, якщо пасажир подорожував один (`FamilySize == 1`), інакше `False`
* Перейменуйте стовпець `Sex` на `Gender`

In [15]:
df_filtered['FamilySize'] = df_filtered['SibSp'] + df_filtered['Parch'] + 1
df_filtered

/tmp/ipykernel_5802/2802492145.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['FamilySize'] = df_filtered['SibSp'] + df_filtered['Parch'] + 1

,PassengerId,Name,Age,Sex,Survived,SibSp,Parch,Fare,Pclass,Embarked,FamilySize
0,1,"Braund, Mr. Owen Harris",22.0,male,0,1,0,7.2500,3,S,2
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,female,1,1,0,71.2833,1,C,2
2,3,"Heikkinen, Miss. Laina",26.0,female,1,0,0,7.9250,3,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,female,1,1,0,53.1000,1,S,2
4,5,"Allen, Mr. William Henry",35.0,male,0,0,0,8.0500,3,S,1
...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",27.0,male,0,0,0,13.0000,2,S,1
887,888,"Graham, Miss. Margaret Edith",19.0,female,1,0,0,30.0000,1,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,female,0,1,2,23.4500,3,S,4
889,890,"Behr, Mr. Karl Howell",26.0,male,1,0,0,30.0000,1,C,1
890,891,"Dooley, Mr. Patrick",32.0,male,0,0,0,7.7500,3,Q,1

In [16]:
df_filtered['IsAlone'] = df_filtered['FamilySize'] == 1
df_filtered

,PassengerId,Name,Age,Sex,Survived,SibSp,Parch,Fare,Pclass,Embarked,FamilySize,IsAlone
0,1,"Braund, Mr. Owen Harris",22.0,male,0,1,0,7.2500,3,S,2,False
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,female,1,1,0,71.2833,1,C,2,False
2,3,"Heikkinen, Miss. Laina",26.0,female,1,0,0,7.9250,3,S,1,True
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,female,1,1,0,53.1000,1,S,2,False
4,5,"Allen, Mr. William Henry",35.0,male,0,0,0,8.0500,3,S,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",27.0,male,0,0,0,13.0000,2,S,1,True
887,888,"Graham, Miss. Margaret Edith",19.0,female,1,0,0,30.0000,1,S,1,True
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,female,0,1,2,23.4500,3,S,4,False
889,890,"Behr, Mr. Karl Howell",26.0,male,1,0,0,30.0000,1,C,1,True
890,891,"Dooley, Mr. Patrick",32.0,male,0,0,0,7.7500,3,Q,1,True

In [17]:
df_filtered.rename(columns={'Sex': 'Gender'}, inplace=True)
df_filtered

,PassengerId,Name,Age,Gender,Survived,SibSp,Parch,Fare,Pclass,Embarked,FamilySize,IsAlone
0,1,"Braund, Mr. Owen Harris",22.0,male,0,1,0,7.2500,3,S,2,False
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,female,1,1,0,71.2833,1,C,2,False
2,3,"Heikkinen, Miss. Laina",26.0,female,1,0,0,7.9250,3,S,1,True
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,female,1,1,0,53.1000,1,S,2,False
4,5,"Allen, Mr. William Henry",35.0,male,0,0,0,8.0500,3,S,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",27.0,male,0,0,0,13.0000,2,S,1,True
887,888,"Graham, Miss. Margaret Edith",19.0,female,1,0,0,30.0000,1,S,1,True
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,female,0,1,2,23.4500,3,S,4,False
889,890,"Behr, Mr. Karl Howell",26.0,male,1,0,0,30.0000,1,C,1,True
890,891,"Dooley, Mr. Patrick",32.0,male,0,0,0,7.7500,3,Q,1,True

**Task 5.**
* Виведіть усіх жінок, які подорожували в 1-му класі (`Pclass == 1`)
* Знайдіть чоловіків, які їхали з 2 або більше родичами (`FamilySize >= 3`) і не вижили
* Виведіть пасажирів, які заплатили за квиток більше 100

In [18]:
df_filtered[(df_filtered['Gender'] == 'female') & (df_filtered['Pclass'] == 1)]

,PassengerId,Name,Age,Gender,Survived,SibSp,Parch,Fare,Pclass,Embarked,FamilySize,IsAlone
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,female,1,1,0,71.2833,1,C,2,False
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,female,1,1,0,53.1000,1,S,2,False
11,12,"Bonnell, Miss. Elizabeth",58.0,female,1,0,0,26.5500,1,S,1,True
31,32,"Spencer, Mrs. William Augustus (Marie Eugenie)",NaN,female,1,1,0,146.5208,1,C,2,False
52,53,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",49.0,female,1,1,0,76.7292,1,C,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,"Wick, Mrs. George Dennick (Mary Hitchcock)",45.0,female,1,1,1,164.8667,1,S,3,False
862,863,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",48.0,female,1,0,0,25.9292,1,S,1,True
871,872,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",47.0,female,1,1,1,52.5542,1,S,3,False
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",56.0,female,1,0,1,83.1583,1,C,2,False
887,888,"Graham, Miss. Margaret Edith",19.0,female,1,0,0,30.0000,1,S,1,True

In [19]:
df_filtered[(df_filtered['Gender'] == 'male') & (df_filtered['FamilySize'] > 2) & (df_filtered['Survived'] == 0)]

,PassengerId,Name,Age,Gender,Survived,SibSp,Parch,Fare,Pclass,Embarked,FamilySize,IsAlone
7,8,"Palsson, Master. Gosta Leonard",2.0,male,0,3,1,21.0750,3,S,5,False
13,14,"Andersson, Mr. Anders Johan",39.0,male,0,1,5,31.2750,3,S,7,False
16,17,"Rice, Master. Eugene",2.0,male,0,4,1,29.1250,3,Q,6,False
27,28,"Fortune, Mr. Charles Alexander",19.0,male,0,3,2,263.0000,1,S,6,False
48,49,"Samaan, Mr. Youssef",NaN,male,0,2,0,21.6792,3,C,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
819,820,"Skoog, Master. Karl Thorsten",10.0,male,0,3,2,27.9000,3,S,6,False
824,825,"Panula, Master. Urho Abraham",2.0,male,0,4,1,39.6875,3,S,6,False
846,847,"Sage, Mr. Douglas Bullen",NaN,male,0,8,2,69.5500,3,S,11,False
850,851,"Andersson, Master. Sigvard Harald Elias",4.0,male,0,4,2,31.2750,3,S,7,False
860,861,"Hansen, Mr. Claus Peter",41.0,male,0,2,0,14.1083,3,S,3,False

In [20]:
df_filtered[df_filtered['Fare'] > 100]

,PassengerId,Name,Age,Gender,Survived,SibSp,Parch,Fare,Pclass,Embarked,FamilySize,IsAlone
27,28,"Fortune, Mr. Charles Alexander",19.00,male,0,3,2,263.0000,1,S,6,False
31,32,"Spencer, Mrs. William Augustus (Marie Eugenie)",NaN,female,1,1,0,146.5208,1,C,2,False
88,89,"Fortune, Miss. Mabel Helen",23.00,female,1,3,2,263.0000,1,S,6,False
118,119,"Baxter, Mr. Quigg Edmond",24.00,male,0,0,1,247.5208,1,C,2,False
195,196,"Lurette, Miss. Elise",58.00,female,1,0,0,146.5208,1,C,1,True
215,216,"Newell, Miss. Madeleine",31.00,female,1,1,0,113.2750,1,C,2,False
258,259,"Ward, Miss. Anna",35.00,female,1,0,0,512.3292,1,C,1,True
268,269,"Graham, Mrs. William Thompson (Edith Junkins)",58.00,female,1,0,1,153.4625,1,S,2,False
269,270,"Bissette, Miss. Amelia",35.00,female,1,0,0,135.6333,1,S,1,True
297,298,"Allison, Miss. Helen Loraine",2.00,female,0,1,2,151.5500,1,S,4,False
299,300,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",50.00,female,1,0,1,247.5208,1,C,2,False
305,306,"Allison, Master. Hudson Trevor",0.92,male,1,1,2,151.5500,1,S,4,False
306,307,"Fleming, Miss. Margaret",NaN,female,1,0,0,110.8833,1,C,1,True
307,308,"Penasco y Castellana, Mrs. Victor de Satode (M...",17.00,female,1,1,0,108.9000,1,C,2,False
311,312,"Ryerson, Miss. Emily Borie",18.00,female,1,2,2,262.3750,1,C,5,False
318,319,"Wick, Miss. Mary Natalie",31.00,female,1,0,2,164.8667,1,S,3,False
319,320,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",40.00,female,1,1,1,134.5000,1,C,3,False
325,326,"Young, Miss. Marie Grice",36.00,female,1,0,0,135.6333,1,C,1,True
332,333,"Graham, Mr. George Edward",38.00,male,0,0,1,153.4625,1,S,2,False
334,335,"Frauenthal, Mrs. Henry William (Clara Heinshei...",NaN,female,1,1,0,133.6500,1,S,2,False
337,338,"Burns, Miss. Elizabeth Margaret",41.00,female,1,0,0,134.5000,1,C,1,True
341,342,"Fortune, Miss. Alice Elizabeth",24.00,female,1,3,2,263.0000,1,S,6,False
373,374,"Ringhini, Mr. Sante",22.00,male,0,0,0,135.6333,1,C,1,True
377,378,"Widener, Mr. Harry Elkins",27.00,male,0,0,2,211.5000,1,C,3,False
380,381,"Bidois, Miss. Rosalie",42.00,female,1,0,0,227.5250,1,C,1,True
390,391,"Carter, Mr. William Ernest",36.00,male,1,1,2,120.0000,1,S,4,False
393,394,"Newell, Miss. Marjorie",23.00,female,1,1,0,113.2750,1,C,2,False
435,436,"Carter, Miss. Lucile Polk",14.00,female,1,1,2,120.0000,1,S,4,False
438,439,"Fortune, Mr. Mark",64.00,male,0,1,4,263.0000,1,S,6,False
498,499,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",25.00,female,0,1,2,151.5500,1,S,4,False
505,506,"Penasco y Castellana, Mr. Victor de Satode",18.00,male,0,1,0,108.9000,1,C,2,False
527,528,"Farthing, Mr. John",NaN,male,0,0,0,221.7792,1,S,1,True
537,538,"LeRoy, Miss. Bertha",30.00,female,1,0,0,106.4250,1,C,1,True
544,545,"Douglas, Mr. Walter Donald",50.00,male,0,1,0,106.4250,1,C,2,False
550,551,"Thayer, Mr. John Borland Jr",17.00,male,1,0,2,110.8833,1,C,3,False
557,558,"Robbins, Mr. Victor",NaN,male,0,0,0,227.5250,1,C,1,True
581,582,"Thayer, Mrs. John Borland (Marian Longstreth M...",39.00,female,1,1,1,110.8833,1,C,3,False
609,610,"Shutes, Miss. Elizabeth W",40.00,female,1,0,0,153.4625,1,S,1,True
659,660,"Newell, Mr. Arthur Webster",58.00,male,0,0,2,113.2750,1,C,3,False
660,661,"Frauenthal, Dr. Henry William",50.00,male,1,2,0,133.6500,1,S,3,False
679,680,"Cardeza, Mr. Thomas Drake Martinez",36.00,male,1,0,1,512.3292,1,C,2,False
689,690,"Madill, Miss. Georgette Alexandra",15.00,female,1,0,1,211.3375,1,S,2,False
698,699,"Thayer, Mr. John Borland",49.00,male,0,1,1,110.8833,1,C,3,False
700,701,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",18.00,female,1,1,0,227.5250,1,C,2,False
708,709,"Cleaver, Miss. Alice",22.00,female,1,0,0,151.5500,1,S,1,True
716,717,"Endres, Miss. Caroline Louise",38.00,female,1,0,0,227.5250,1,C,1,True
730,731,"Allen, Miss. Elisabeth Walton",29.00,female,1,0,0,211.3375,1,S,1,True
737,738,"Lesurer, Mr. Gustave J",35.00,male,1,0,0,512.3292,1,C,1,True
742,743,"Ryerson, Miss. Susan Parker ""Suzette""",21.00,female,1,2,2,262.3750,1,C,5,False
763,764,"Carter, Mrs. William Ernest (Lucile Polk)",36.00,female,1,1,2,120.0000,1,S,4,False
779,780,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",43.00,female,1,0,1,211.3375,1,S,2,False
802,803,"Carter, Master. William Thornton II",11.00,male,1,1,2,120.0000,1,S,4,False
856,857,"Wick, Mrs. George Dennick (Mary Hitchcock)",45.00,female,1,1,1,164.8667,1,S,3,False

**Task 6.**
* Відсортуйте пасажирів за вартістю квитка у спадному порядку
* Виведіть 10 наймолодших пасажирів, які вижили
* Відсортуйте спочатку за `Pclass`, а потім за `Age` у зростаючому порядку

In [21]:
df_filtered.sort_values('Fare', ascending=False, inplace=True)

In [22]:
df_filtered

,PassengerId,Name,Age,Gender,Survived,SibSp,Parch,Fare,Pclass,Embarked,FamilySize,IsAlone
679,680,"Cardeza, Mr. Thomas Drake Martinez",36.0,male,1,0,1,512.3292,1,C,2,False
258,259,"Ward, Miss. Anna",35.0,female,1,0,0,512.3292,1,C,1,True
737,738,"Lesurer, Mr. Gustave J",35.0,male,1,0,0,512.3292,1,C,1,True
88,89,"Fortune, Miss. Mabel Helen",23.0,female,1,3,2,263.0000,1,S,6,False
438,439,"Fortune, Mr. Mark",64.0,male,0,1,4,263.0000,1,S,6,False
...,...,...,...,...,...,...,...,...,...,...,...,...
806,807,"Andrews, Mr. Thomas Jr",39.0,male,0,0,0,0.0000,1,S,1,True
815,816,"Fry, Mr. Richard",NaN,male,0,0,0,0.0000,1,S,1,True
466,467,"Campbell, Mr. William",NaN,male,0,0,0,0.0000,2,S,1,True
481,482,"Frost, Mr. Anthony Wood ""Archie""",NaN,male,0,0,0,0.0000,2,S,1,True
822,823,"Reuchlin, Jonkheer. John George",38.0,male,0,0,0,0.0000,1,S,1,True

In [28]:
df_live = df_filtered[df_filtered['Survived'] == 1]
df_live.sort_values('Age', inplace=True)
df_live.head(10)

/tmp/ipykernel_5802/3739599997.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_live.sort_values('Age', inplace=True)

,PassengerId,Name,Age,Gender,Survived,SibSp,Parch,Fare,Pclass,Embarked,FamilySize,IsAlone
803,804,"Thomas, Master. Assad Alexander",0.42,male,1,0,1,8.5167,3,C,2,False
755,756,"Hamalainen, Master. Viljo",0.67,male,1,1,1,14.5000,2,S,3,False
469,470,"Baclini, Miss. Helene Barbara",0.75,female,1,2,1,19.2583,3,C,4,False
644,645,"Baclini, Miss. Eugenie",0.75,female,1,2,1,19.2583,3,C,4,False
78,79,"Caldwell, Master. Alden Gates",0.83,male,1,0,2,29.0000,2,S,3,False
831,832,"Richards, Master. George Sibley",0.83,male,1,1,1,18.7500,2,S,3,False
305,306,"Allison, Master. Hudson Trevor",0.92,male,1,1,2,151.5500,1,S,4,False
172,173,"Johnson, Miss. Eleanor Ileen",1.00,female,1,1,1,11.1333,3,S,3,False
827,828,"Mallet, Master. Andre",1.00,male,1,0,2,37.0042,2,C,3,False
183,184,"Becker, Master. Richard F",1.00,male,1,2,1,39.0000,2,S,4,False

In [30]:
df_filtered.sort_values(['Pclass', 'Age'], ascending=[True, False])

,PassengerId,Name,Age,Gender,Survived,SibSp,Parch,Fare,Pclass,Embarked,FamilySize,IsAlone
630,631,"Barkworth, Mr. Algernon Henry Wilson",80.0,male,1,0,0,30.0000,1,S,1,True
493,494,"Artagaveytia, Mr. Ramon",71.0,male,0,0,0,49.5042,1,C,1,True
96,97,"Goldschmidt, Mr. George B",71.0,male,0,0,0,34.6542,1,C,1,True
745,746,"Crosby, Capt. Edward Gifford",70.0,male,0,1,1,71.0000,1,S,3,False
54,55,"Ostby, Mr. Engelhart Cornelius",65.0,male,0,0,1,61.9792,1,C,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...
354,355,"Yousif, Mr. Wazli",NaN,male,0,0,0,7.2250,3,C,1,True
598,599,"Boulos, Mr. Hanna",NaN,male,0,0,0,7.2250,3,C,1,True
611,612,"Jardin, Mr. Jose Neto",NaN,male,0,0,0,7.0500,3,S,1,True
825,826,"Flynn, Mr. John",NaN,male,0,0,0,6.9500,3,Q,1,True
411,412,"Hart, Mr. Henry",NaN,male,0,0,0,6.8583,3,Q,1,True

**Task 7.**
Чи впливає розмір сім’ї на шанс виживання?

In [37]:
df_filtered.FamilySize.unique()

array([ 2,  1,  6,  5,  3,  4, 11,  8,  7])

In [42]:
for item in sorted(df_filtered.FamilySize.unique()):
  tmp = df_filtered[df_filtered['FamilySize'] == item]
  print(f'Size: {item}, {tmp.Survived.mean() * 100:.2f}%')

Size: 1, 30.35%
Size: 2, 55.28%
Size: 3, 57.84%
Size: 4, 72.41%
Size: 5, 20.00%
Size: 6, 13.64%
Size: 7, 33.33%
Size: 8, 0.00%
Size: 11, 0.00%

**Task 8.**
Чи були відмінності у виживанні серед пасажирів з різними титулами (Mr, Mrs, Dr тощо)?

In [44]:
def get_person_title(name):
  name = name.split()
  for part in name:
    if part[-1] == '.':
      return part
  return ''

df_filtered['Titule'] = df_filtered.Name.apply(get_person_title)
df_filtered

,PassengerId,Name,Age,Gender,Survived,SibSp,Parch,Fare,Pclass,Embarked,FamilySize,IsAlone,Mr,Titule
679,680,"Cardeza, Mr. Thomas Drake Martinez",36.0,male,1,0,1,512.3292,1,C,2,False,True,Mr.
258,259,"Ward, Miss. Anna",35.0,female,1,0,0,512.3292,1,C,1,True,False,Miss.
737,738,"Lesurer, Mr. Gustave J",35.0,male,1,0,0,512.3292,1,C,1,True,True,Mr.
88,89,"Fortune, Miss. Mabel Helen",23.0,female,1,3,2,263.0000,1,S,6,False,False,Miss.
438,439,"Fortune, Mr. Mark",64.0,male,0,1,4,263.0000,1,S,6,False,True,Mr.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
806,807,"Andrews, Mr. Thomas Jr",39.0,male,0,0,0,0.0000,1,S,1,True,True,Mr.
815,816,"Fry, Mr. Richard",NaN,male,0,0,0,0.0000,1,S,1,True,True,Mr.
466,467,"Campbell, Mr. William",NaN,male,0,0,0,0.0000,2,S,1,True,True,Mr.
481,482,"Frost, Mr. Anthony Wood ""Archie""",NaN,male,0,0,0,0.0000,2,S,1,True,True,Mr.
822,823,"Reuchlin, Jonkheer. John George",38.0,male,0,0,0,0.0000,1,S,1,True,False,Jonkheer.