<a href="https://colab.research.google.com/github/cpython-projects/python_da_17_03_26/blob/main/lesson_12_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Опис набору даних

Набір даних (**ecommerce_data.csv**, https://raw.githubusercontent.com/cpython-projects/python_da_17_03_26/refs/heads/main/ecommerce.csv) містить **40 рядків** і **19 стовпців**, що представляють транзакції у сфері електронної комерції. Нижче наведено опис кожного стовпця:

| Назва стовпця      | Опис                                                                       |
| ------------------ | -------------------------------------------------------------------------- |
| `order_id`         | Унікальний ідентифікатор замовлення.                                       |
| `customer_id`      | Унікальний ідентифікатор клієнта.                                          |
| `order_date`       | Дата оформлення замовлення (у форматі РРРР-ММ-ДД).                         |
| `product_id`       | Унікальний ідентифікатор придбаного товару.                                |
| `product_name`     | Назва товару.                                                              |
| `category`         | Категорія товару (наприклад, Електроніка, Одяг тощо).                      |
| `price`            | Ціна за одиницю товару.                                                    |
| `quantity`         | Кількість придбаних одиниць.                                               |
| `weight`           | Вага товару (у кг, зберігається як рядок).                                 |
| `discount`         | Застосована знижка (у вигляді десяткового дробу, наприклад, 0.10 для 10%). |
| `shipping_cost`    | Вартість доставки товару (наявні пропущені значення).                      |
| `payment_method`   | Метод оплати (наприклад, Кредитна картка, PayPal, Дебет).                  |
| `delivery_status`  | Статус доставки (Доставлено, Відправлено, В обробці тощо).                 |
| `customer_city`    | Місто клієнта.                                                             |
| `customer_state`   | Штат клієнта.                                                              |
| `customer_country` | Країна клієнта.                                                            |
| `return_requested` | Чи було запитано повернення (1 = Так, 0 = Ні).                             |
| `review_score`     | Оцінка клієнта (за 5-бальною шкалою, є пропущені значення).                |
| `days_to_deliver`  | Кількість днів на доставку (є пропущені значення).                         |

---

In [1]:
import pandas as pd

In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/cpython-projects/python_da_17_03_26/refs/heads/main/ecommerce.csv')
df

,order_id,customer_id,order_date,product_id,product_name,category,price,quantity,weight,discount,shipping_cost,payment_method,delivery_status,customer_city,customer_state,customer_country,return_requested,review_score,days_to_deliver
0,1001,C101,2023-01-15,P001,Smartphone X,Electronics,599.99,1,0.5kg,0.10,5.99,Credit Card,Delivered,New York,NY,USA,0,5.0,3.0
1,1002,C102,2023-01-16,P002,Laptop Pro,Electronics,1299.99,1,2.2kg,0.15,12.99,paypal,Delivered,los angeles,CA,USA,1,4.0,5.0
2,1003,C103,2023-01-17,P003,Wireless Earbuds,Electronics,79.99,2,0.1kg,0.00,NaN,Credit Card,Shipped,Chicago,IL,USA,0,NaN,NaN
3,1004,C104,2023-01-18,P004,Smart Watch,Electronics,199.99,1,0.3kg,0.05,4.99,debit,Delivered,Houston,TX,USA,0,5.0,4.0
4,1005,C105,2023-01-19,P005,Tablet Mini,Electronics,299.99,1,0.7kg,NaN,6.99,credit,Processing,PHOENIX,AZ,USA,1,2.0,NaN
5,1006,C106,2023-01-20,P006,Bluetooth Speaker,Electronics,59.99,3,1.1lbs,0.00,8.99,PayPal,Delivered,Philadelphia,PA,USA,0,4.0,6.0
6,1007,C107,2023-01-21,P007,Fitness Tracker,Electronics,49.99,1,0.05kg,0.10,3.49,Debit Card,Delivered,San Antonio,TX,USA,0,5.0,3.0
7,1008,C108,2023-01-22,P008,4K TV,Electronics,899.99,1,15.4kg,0.25,NaN,Credit Card,Shipped,San Diego,CA,USA,0,NaN,NaN
8,1009,C109,2023-01-23,P009,Gaming Console,Electronics,499.99,1,3.5kg,NaN,15.99,Credit Card,Processing,Dallas,TX,USA,1,3.0,NaN
9,1010,C110,2023-01-24,P010,DSLR Camera,Electronics,799.99,1,1.2kg,0.00,12.99,PayPal,Delivered,dallas,CA,USA,0,5.0,5.0
10,1011,C111,2023-01-25,P011,Action Camera,Electronics,199.99,2,0.3kg,0.15,6.99,Credit Card,Shipped,Austin,TX,USA,0,4.0,4.0
11,1012,C112,2023-01-26,P012,External SSD,Electronics,149.99,1,0.1kg,0.00,4.99,Debit Card,delivered,Jacksonville,FL,USA,0,5.0,3.0
12,1013,C113,2023-01-27,P013,Wireless Mouse,Electronics,29.99,3,0.2kg,NaN,NaN,PayPal,processing,Fort Worth,TX,U.S.A,1,1.0,NaN
13,1014,C114,2023-01-28,P014,Mechanical Keyboard,Electronics,99.99,1,1.1kg,0.10,8.99,Credit Card,Delivered,Columbus,OH,United States,0,4.0,4.0
14,1015,C115,2023-01-29,P015,"Monitor 27""",Electronics,249.99,1,5.5kg,NaN,14.99,Debit Card,Shipped,Charlotte,NC,USA,0,3.0,NaN
15,1016,C116,2023-01-30,P016,Printer,Electronics,179.99,1,8.8kg,0.20,19.99,Credit Card,Processing,San Francisco,CA,USA,0,5.0,NaN
16,1017,C117,2023-01-31,P017,Projector,Electronics,349.99,1,3.3kg,0.10,12.99,PayPal,Delivered,Indianapolis,IN,USA,0,4.0,5.0
17,1018,C118,2023-02-01,P018,Smart Bulb,Smart Home,29.99,4,0.2kg,0.00,3.99,Debit Card,Delivered,Seattle,WA,USA,0,5.0,3.0
18,1019,C119,2023-02-02,P019,Robot Vacuum,Smart Home,299.99,1,4.4kg,NaN,NaN,Credit Card,Shipped,Denver,CO,USA,0,4.0,NaN
19,1020,C120,2023-02-03,P020,Air Purifier,Smart Home,199.99,1,5.5kg,0.05,12.99,PayPal,Processing,Washington,DC,USA,0,5.0,NaN
20,1021,C101,2023-02-04,P001,Smartphone X,Electronics,599.99,1,0.5kg,0.10,5.99,Credit Card,Delivered,N.Y.,NY,USA,0,5.0,3.0
21,1022,C122,2023-02-05,P022,Docking Station,Electronics,89.99,1,0.4kg,0.00,4.99,debit card,Delivered,Boston,MA,USA,0,4.0,4.0
22,1023,C123,2023-02-06,P023,Webcam,Electronics,69.99,1,0.2kg,NaN,NaN,PayPal,Shipped,El Paso,TX,USA,0,3.0,NaN
23,1024,C124,2023-02-07,P024,Microphone,Electronics,129.99,1,0.5kg,0.10,5.99,Credit Card,Processing,Nashville,TN,USA,0,5.0,NaN
24,1025,C125,2023-02-08,P025,Graphics Tablet,Electronics,89.99,1,0.6kg,NaN,4.99,Debit Card,Delivered,Detroit,MI,USA,0,4.0,5.0
25,1026,C126,2023-02-09,P026,E-reader,Electronics,119.99,1,0.3kg,0.15,NaN,PayPal,Delivered,Portland,OR,USA,0,5.0,4.0
26,1027,C127,2023-02-10,P027,Smart Plug,Smart Home,24.99,1,0.1kg,0.00,2.99,Credit Card,shipped,Memphis,TN,USA,0,4.0,NaN
27,1028,C128,2023-02-11,P028,NAS Drive,Electronics,299.99,1,1.8kg,NaN,NaN,Debit Card,processing,Oklahoma City,OK,USA,0,3.0,NaN
28,1029,C129,2023-02-12,P029,VR Headset,Electronics,349.99,1,0.7kg,0.05,8.99,PayPal,Delivered,Las Vegas,NV,USA,0,5.0,4.0
29,1030,C130,2023-02-13,P030,Drone,Electronics,499.99,1,1.2kg,NaN,12.99,Credit Card,Delivered,Louisville,KY,USA,0,4.0,3.0
30,1028,C128,2023-02-11,P028,NAS Drive,Electronics,299.99,1,1.8kg,NaN,NaN,Debit Card,processing,Oklahoma City,OK,USA,0,3.0,NaN
31,1016,C116,2023-01-30,P016,Printer,Electronics,179.99,1,8.8kg,0.20,19.99,Credit Card,Processing,San Francisco,CA,USA,0,5.0,NaN
32,1024,C124,2023-02-07,P024,Microphone,Electronics,129.99,1,0.5kg,0.10,5.99,Credit Card,Processing,Nashville,TN,USA,0,5.0,NaN
33,1018,C118,2023-02-01,P018,Smart Bulb,Smart Home,29.99,4,0.2kg,0.00,3.99,Debit Card,Delivered,Seattle,WA,USA,0,5.0,3.0
34,1009,C109,2023-01-23,P009,Gaming Console,Electronics,499.99,1,3.5kg,NaN,15.99,Credit Card,Processing,Dallas,TX,USA,1,3.0,NaN
35,1007,C107,2023-01-21,P007,Fitness Tracker,Electronics,59.99,1,0.05kg,0.10,3.49,Debit Card,Delivered,San Antonio,TX,USA,0,5.0,3.0
36,1028,C128,2023-02-11,P028,NAS Drive,Electronics,299.99,2,1.8kg,NaN,NaN,Debit Card,Processing,Oklahoma City,OK,USA,0,3.0,NaN
37,2006,C106,2023-01-20,P006,Bluetooth Speaker,Electronics,59.99,3,1.1lbs,0.00,8.99,PayPal,Delivered,Philadelphia,PA,USA,0,4.0,6.0
38,1013,C113,2023-01-27,P013,Wireless Mouse,Electronics,29.99,3,0.2kg,NaN,NaN,PayPal,Delivered,Fort Worth,TX,U.S.A,1,1.0,NaN
39,1025,C125,2023-02-08,P025,Graphics Tablet,Electronics,99.99,1,0.6kg,NaN,4.99,PayPal,Delivered,Detroit,MI,USA,0,4.0,5.0

**Завдання 1.** Робота з дублікатами

In [17]:
df.duplicated().sum()

np.int64(5)

In [18]:
df.drop_duplicates(inplace=True) # None

In [19]:
df.shape

(35, 19)

**Завдання 2.** Обробка некоректних форматів

* Числові дані подані у вигляді рядків
* Дати подані у вигляді рядків
* Категоріальні дані подані у вигляді рядків/чисел

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35 entries, 0 to 39
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          35 non-null     int64
 1   customer_id       35 non-null     object
 2   order_date        35 non-null     object
 3   product_id        35 non-null     object
 4   product_name      35 non-null     object
 5   category          35 non-null     object
 6   price             35 non-null     float64
 7   quantity          35 non-null     int64
 8   weight            35 non-null     object
 9   discount          23 non-null     float64
 10  shipping_cost     26 non-null     float64
 11  payment_method    35 non-null     object
 12  delivery_status   35 non-null     object
 13  customer_city     35 non-null     object
 14  customer_state    35 non-null     object
 15  customer_country  35 non-null     object
 16  return_requested  35 non-null     int64
 17  review_score      33 non-null     float64
 18  days_to_deliver   20 non-null     float64
dtypes: float64(5), int64(3), object(11)
memory usage: 5.5+ KB

In [21]:
df.columns.to_list()

['order_id',
 'customer_id',
 'order_date',
 'product_id',
 'product_name',
 'category',
 'price',
 'quantity',
 'weight',
 'discount',
 'shipping_cost',
 'payment_method',
 'delivery_status',
 'customer_city',
 'customer_state',
 'customer_country',
 'return_requested',
 'review_score',
 'days_to_deliver']

In [22]:
df.order_date.unique()

array(['2023-01-15', '2023-01-16', '2023-01-17', '2023-01-18',
       '2023-01-19', '2023-01-20', '2023-01-21', '2023-01-22',
       '2023-01-23', '2023-01-24', '2023-01-25', '2023-01-26',
       '2023-01-27', '2023-01-28', '2023-01-29', '2023-01-30',
       '2023-01-31', '2023-02-01', '2023-02-02', '2023-02-03',
       '2023-02-04', '2023-02-05', '2023-02-06', '2023-02-07',
       '2023-02-08', '2023-02-09', '2023-02-10', '2023-02-11',
       '2023-02-12', '2023-02-13'], dtype=object)

In [24]:
df['order_date'] = pd.to_datetime(df.order_date, format='%Y-%m-%d', errors='coerce')

In [28]:
df['category'] = df.category.astype('category')

In [30]:
df['payment_method'] = df.payment_method.str.strip().str.lower()

In [32]:
df.payment_method.replace(
    {
        'credit card': 'credit',
        'debit card': 'debit'
    },
    inplace=True
)

In [34]:
df['payment_method'] = df.payment_method.astype('category')

In [36]:
df['delivery_status'] = df.delivery_status.str.lower()

In [ ]:
for column_name in []:
  df[column_name] = df[column_name].str.lower()

In [37]:
df['delivery_status'] = df.delivery_status.astype('category')

In [39]:
def weight_converter(item):
  item = item.lower()
  if 'kg' in item:
    return float(item.replace('kg', ''))
  if 'lbs' in item:
    return float(item.replace('lbs', '')) * 0.45

  return None


df['weight_kg'] = df.weight.apply(weight_converter)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35 entries, 0 to 39
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          35 non-null     int64
 1   customer_id       35 non-null     object
 2   order_date        35 non-null     datetime64[ns]
 3   product_id        35 non-null     object
 4   product_name      35 non-null     object
 5   category          35 non-null     category
 6   price             35 non-null     float64
 7   quantity          35 non-null     int64
 8   weight            35 non-null     object
 9   discount          35 non-null     float64
 10  shipping_cost     26 non-null     float64
 11  payment_method    35 non-null     category
 12  delivery_status   35 non-null     category
 13  customer_city     35 non-null     object
 14  customer_state    35 non-null     object
 15  customer_country  35 non-null     object
 16  return_requested  35 non-null     int64
 17  review_score      33 non-null     float64
 18  days_to_deliver   20 non-null     float64
 19  weight_kg         35 non-null     float64
dtypes: category(3), datetime64[ns](1), float64(6), int64(3), object(7)
memory usage: 5.4+ KB

**Завдання 3.** Робота з пропущеними значеннями

In [42]:
# discount
# shipping_cost
# review_score
# days_to_deliver
df['discount'] = df.discount.fillna(0)

In [49]:
df[~df['shipping_cost'].notna()]

,order_id,customer_id,order_date,product_id,product_name,category,price,quantity,weight,discount,shipping_cost,payment_method,delivery_status,customer_city,customer_state,customer_country,return_requested,review_score,days_to_deliver,weight_kg
2,1003,C103,2023-01-17,P003,Wireless Earbuds,Electronics,79.99,2,0.1kg,0.00,NaN,credit,shipped,Chicago,IL,USA,0,NaN,NaN,0.1
7,1008,C108,2023-01-22,P008,4K TV,Electronics,899.99,1,15.4kg,0.25,NaN,credit,shipped,San Diego,CA,USA,0,NaN,NaN,15.4
12,1013,C113,2023-01-27,P013,Wireless Mouse,Electronics,29.99,3,0.2kg,0.00,NaN,paypal,processing,Fort Worth,TX,U.S.A,1,1.0,NaN,0.2
18,1019,C119,2023-02-02,P019,Robot Vacuum,Smart Home,299.99,1,4.4kg,0.00,NaN,credit,shipped,Denver,CO,USA,0,4.0,NaN,4.4
22,1023,C123,2023-02-06,P023,Webcam,Electronics,69.99,1,0.2kg,0.00,NaN,paypal,shipped,El Paso,TX,USA,0,3.0,NaN,0.2
25,1026,C126,2023-02-09,P026,E-reader,Electronics,119.99,1,0.3kg,0.15,NaN,paypal,delivered,Portland,OR,USA,0,5.0,4.0,0.3
27,1028,C128,2023-02-11,P028,NAS Drive,Electronics,299.99,1,1.8kg,0.00,NaN,debit,processing,Oklahoma City,OK,USA,0,3.0,NaN,1.8
36,1028,C128,2023-02-11,P028,NAS Drive,Electronics,299.99,2,1.8kg,0.00,NaN,debit,processing,Oklahoma City,OK,USA,0,3.0,NaN,1.8
38,1013,C113,2023-01-27,P013,Wireless Mouse,Electronics,29.99,3,0.2kg,0.00,NaN,paypal,delivered,Fort Worth,TX,U.S.A,1,1.0,NaN,0.2

In [50]:
df['review_score '] = df.review_score.fillna(df.review_score.median())

**Завдання 4.** Визначення найприбутковіших товарів

**Необхідні ознаки:** `product_name`, `price`, `quantity`, `discount`

In [51]:
df['total'] = df.price * df.quantity * (1 - df.discount)

In [53]:
df.sort_values(by='total', ascending=False, inplace=True)

In [54]:
df.head(10)

,order_id,customer_id,order_date,product_id,product_name,category,price,quantity,weight,discount,...,delivery_status,customer_city,customer_state,customer_country,return_requested,review_score,days_to_deliver,weight_kg,review_score,total
1,1002,C102,2023-01-16,P002,Laptop Pro,Electronics,1299.99,1,2.2kg,0.15,...,delivered,los angeles,CA,USA,1,4.0,5.0,2.2,4.0,1104.9915
9,1010,C110,2023-01-24,P010,DSLR Camera,Electronics,799.99,1,1.2kg,0.00,...,delivered,dallas,CA,USA,0,5.0,5.0,1.2,5.0,799.9900
7,1008,C108,2023-01-22,P008,4K TV,Electronics,899.99,1,15.4kg,0.25,...,shipped,San Diego,CA,USA,0,NaN,NaN,15.4,4.0,674.9925
36,1028,C128,2023-02-11,P028,NAS Drive,Electronics,299.99,2,1.8kg,0.00,...,processing,Oklahoma City,OK,USA,0,3.0,NaN,1.8,3.0,599.9800
0,1001,C101,2023-01-15,P001,Smartphone X,Electronics,599.99,1,0.5kg,0.10,...,delivered,New York,NY,USA,0,5.0,3.0,0.5,5.0,539.9910
20,1021,C101,2023-02-04,P001,Smartphone X,Electronics,599.99,1,0.5kg,0.10,...,delivered,N.Y.,NY,USA,0,5.0,3.0,0.5,5.0,539.9910
8,1009,C109,2023-01-23,P009,Gaming Console,Electronics,499.99,1,3.5kg,0.00,...,processing,Dallas,TX,USA,1,3.0,NaN,3.5,3.0,499.9900
29,1030,C130,2023-02-13,P030,Drone,Electronics,499.99,1,1.2kg,0.00,...,delivered,Louisville,KY,USA,0,4.0,3.0,1.2,4.0,499.9900
10,1011,C111,2023-01-25,P011,Action Camera,Electronics,199.99,2,0.3kg,0.15,...,shipped,Austin,TX,USA,0,4.0,4.0,0.3,4.0,339.9830
28,1029,C129,2023-02-12,P029,VR Headset,Electronics,349.99,1,0.7kg,0.05,...,delivered,Las Vegas,NV,USA,0,5.0,4.0,0.7,5.0,332.4905

**Завдання 5.** Аналіз середнього часу доставки за країнами

**Необхідні ознаки:** `customer_country`, `days_to_deliver`

In [55]:
df.customer_country.unique()

array(['USA', 'United States', 'U.S.A'], dtype=object)

In [56]:
df.drop(columns=['customer_country'], inplace=True)

In [58]:
import math

math.ceil(df.days_to_deliver.mean())

5